### ISSUE TITLE
gs:DownloadAnimation timeout if data is on database.

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/eumetsat-EOWS#137]
A gs:DownloadAnimation process fails after successfully generating a few frames of an animation.

I tracked down an internal WMS request that hangs after a few times it is run.

The failing internal request can be replicated with a regular GetMap request.

Example of failing request: http://pf-docker2.eoss-cloud.it/geoserver-master/wms?SERVICE=WMS&VERSION=1.1.0&REQUEST=GetMap&FORMAT=image/png&TRANSPARENT=true&LAYERS=eumetsat:metopa_ascat&TIME=2018-04-19T20:05:00.000Z&WIDTH=1024&HEIGHT=700&SRS=EPSG:4326&BBOX=-119.06789472247578,-85.8700479839779,125.44382402752422,81.2979207660221&access_token=3c749516-9294-3a7f-9757-c2ffbd234849

Note: access_token is not valid anymore

The request takes 3 seconds (due to database query time), but if you try the request many times it periodically fails.

**Comment by Gnafu** [comment]
The gs:DownloadAnimation request body that triggers this issue is https://pastebin.com/tFM9YvZB

**Comment by aaime** [comment]
Lots of layers, don't have all of them... will try with just metopa/sosi and see if I can reproduce

**Comment by aaime** [comment]
Tests suggests the slowdown happens when prepared statements are enabled.
The slowdown happens after 5 calls since that's when server side prepared statements are actually getting used, with a generic plan that does not account for actual parameter values anymore:
https://jdbc.postgresql.org/documentation/head/server-prepare.html

Server side prepared statement can be disabled using a JDBC url parameter, ``prepareThreshold=0``, see previous link but also:
https://jdbc.postgresql.org/documentation/head/connect.html#connection-parameters

We need to assess if doing so solves the problem while at the same time not slowing down inserts in import.

**Comment by Gnafu** [comment]
Due to an existing bug in the jdbc driver shipped with GeoServer 2.14.x that parameter has no effect in our use case (https://github.com/pgjdbc/pgjdbc/issues/869)

Using postgresql-42.1.4.jar it will work.

If no objections, I'll edit the build to update that jar

**Comment by aaime** [comment]
so is this done?

**Comment by simboss** [comment]
@Gnafu ?

**Comment by Gnafu** [comment]
yes
