### ISSUE TITLE
The file downloaded through a GetMap request shall have a filename reporting the name of the product and the timestamp

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/eumetsat-EOWS#154]
**WMS-PLP-API-1921**

- Fix extensions for all response objects associated to GetMap. 
- Allow configurable templating for the output file name with request parameters.
- Configure the templates for the deployment

**Comment by aaime** [comment]
The client can add the following two query parameters to control the output headers:

- FILENAME to specify the name of the generated file
- CONTENT-DISPOSITION to eventually force a certain download 

Example: ``...?FILENAME=myFile.png&CONTENT-DISPOSITION=attachment`` will generate a response with the header ``Content-disposition: attachment; filname=myFile.png``

Live example, forces the browser to download a file named ``foobar.png`` instead of ``syria_vtp-crop_land_s.png``:
http://ows.geo-solutions.it/geoserver/syria_vtp/wms?service=WMS&version=1.1.0&request=GetMap&layers=syria_vtp%3Acrop_land_s&bbox=35.7481171000001%2C32.3140861000001%2C42.3718427000001%2C37.3215091000001&width=768&height=580&srs=EPSG%3A4326&format=image/png&filename=foobar.png&content-disposition=attachment

**Comment by Gnafu** [comment]
Demoed to the client
