### ISSUE TITLE
The file downloaded through a GetCoverage request shall have a filename reporting the name of the product and indications about time start/end

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/eumetsat-EOWS#155]
**WMS-PLP-API-1921**

- Fix extensions for all response objects associated to GetCoverage. 
- Allow configurable templating for the output file name with request parameters.
- Configure the templates for the deployment

**Comment by aaime** [comment]
The client can add the following two query parameters to control the output headers:

- FILENAME to specify the name of the generated file
- CONTENT-DISPOSITION to eventually force a certain download 

Example: ``...?FILENAME=myFile.png&CONTENT-DISPOSITION=attachment`` will generate a response with the header ``Content-disposition: attachment; filname=myFile.png``

Live example, forces the browser to download a file named ``dem.tif`` instead of ``vtp_Daraa_DTED``:
http://ows.geo-solutions.it/geoserver/wcs?service=WCS&version=2.0.0&request=GetCoverage&coverageId=vtp%3ADaraa_DTED&filename=dem.tif&content-disposition=attachment
