### ISSUE TITLE
Beaufort scale for Metop A ASCAT

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/eumetsat-EOWS#169]
**WMS-PLP-ACC-1540**
The Metop A ASCAT legend and colour scale shall be consistent with the Beaufort scale.

**Comment by simboss** [comment]
"Looking at this https://en.wikipedia.org/wiki/Beaufort_scale definition.
We are proposing to modify the style for the vector wind data based on wind intensity that would replicate the colors of the Beaufort Wind Scale at the bottom of the page for the arrows visualization. The wind barbs will not be touched."

**Comment by Gnafu** [comment]
Before
![before_1.jpg](https://images.zenhubusercontent.com/5cd44174fe59e12f2130c49d/a5b58b2c-d61a-40c9-b0b3-6775120e6cb8)

After (with Beaufort scale)
![after_1.jpg](https://images.zenhubusercontent.com/5cd44174fe59e12f2130c49d/23c97d2d-2a83-4b9c-ab99-5a3763b951b0)

@simboss I did not change the windbarbs colors because "The wind barbs will not be touched." is it correct? There will be a color change when zooming in.

![before_2.jpg](https://images.zenhubusercontent.com/5cd44174fe59e12f2130c49d/a93b9e08-79f4-4b71-aea9-988b1c8d0731)

**Comment by simboss** [comment]
@Gnafu send an email to guillame and fabrizio with the pictures asking for feedback.

I have no idea where windbarbs comment comes from. Can you elaborate before sending that email?

**Comment by Gnafu** [comment]
It comes from the task sheet: https://docs.google.com/spreadsheets/d/1V6g7VumTAo0AZqgdq7nMYKw98yiF9OILIblPbfa6dsw/edit#gid=709687092&range=G17
I think you made that comment, so I'm asking.

**Comment by simboss** [comment]
You should adapt their colors as well, like for the arrows.

**Comment by Gnafu** [comment]
Will do

**Comment by Gnafu** [comment]
New colors:

![after_2.jpg](https://images.zenhubusercontent.com/5cd44174fe59e12f2130c49d/67a12758-5cd4-49a6-b9ab-d92e7e7635c3)

**Comment by Gnafu** [comment]
Mail sent, waiting for feedback

**Comment by simboss** [comment]
great work @Gnafu
