### ISSUE TITLE
Dark Background Layer

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/eumetsat-EOWS#171]
**WMS-PLP-ACC-1550**
A base layer featuring dark colours (especially for water bodies) shall be available, in order to optimally visualize the Metop A ASCAT Wind collection.

**Comment by simboss** [comment]
@allyoucanmap we can create a couple of background maps for this purpose.
Notice that EUM does not need to go high resolution background, so no OSM data is really needed ( check what they have now).

I like [Stamen Toner](http://maps.stamen.com/toner/) a lot but it is probably too dark.
I also like [MapBox Dark](https://api.mapbox.com/styles/v1/mapbox/dark-v10.html?title=true&access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4M29iazA2Z2gycXA4N2pmbDZmangifQ.-g_vE53SD2WrJ6tFX7QHmA#0.81/0/0).

I guess what they have in mind is something similar to the [Windy](https://www.windy.com) background since we want to use it for showing wind arrows in a more visible way. We could also use the Gray Earth.

**Comment by Gnafu** [comment]
Please note that ASCAT colors will change to match the colors in the wikipedia [Beaufort Scale page](https://en.m.wikipedia.org/wiki/Beaufort_scale)
See #169

**Comment by simboss** [comment]
reassigned @aaime

**Comment by aaime** [comment]
So in summary after discussion, we want to:

- Setup server side mapbox GL styles like [OpenMapTile's](https://openmaptiles.org/) positron and dark matter (DM first), to be used against the postgis database. This requires some mapbox styles translator fixes (yet to be determined)
- Setup server side also the [Gray Earth](https://www.naturalearthdata.com/downloads/10m-raster-data/) background image from Natural Earth

**Comment by simboss** [comment]
As per our discussion, I would also make available [this](https://www.naturalearthdata.com/downloads/10m-gray-earth/gray-earth-with-shaded-relief-ocean-bottom-and-drainages/) raster layer.

**Comment by simboss** [comment]
If you want to have an idea about data resolution, [this](https://wms.eumetsat.int/) is the portal.
Ask @Gnafu for credentials, I can give you an intro.

**Comment by Gnafu** [comment]
Demo map here: https://dev.mapstore.geo-solutions.it/mapstore/#/viewer/openlayers/20985
@aaime I think you are working on another layer, can you please link it here when you are done?

**Comment by Gnafu** [comment]
@aaime I would like to set up the database needed for this, where can I find it?
Thank you

**Comment by Gnafu** [comment]
Link to our server have been sent to Stefano Marra for the client side integration testing

**Comment by Gnafu** [comment]
Setting up a cascading WMS on DEV environment to our maps server.

The final delivery will include NaturalEarth (not OSM) and a 2.16 back-port (not a 2.17 upgrade): this will ensure a faster delivery of the background layers.

**Comment by aaime** [comment]
@Gnafu we are looking at delivery options. 
The latest is that we'll provide a GeoPackage with all the data, that can be easily moved around.

The GeoPackage will replace the shapefile database, but in addition, will contain a simplified version of the places, waterway and waterareas OSM layers, that I'll produce using imposm3 and ogr2ogr. 

Since we have to cover the entire planet (right @simboss ?), in order to get there we'll have to download the full planet file and run the imposm process... the [planet file](https://planet.openstreetmap.org/) is 50GB, and imposm3 will need some extra storage to run its cache and eventually insert in the database. 
@randomorder do we have enough disk space?

Another possibility I have found is this site, providing geopackge extracts of single themed layers for the whole planet: https://download.osmdata.xyz/
However, summing up the places, waterway and water layers, it's still 10GB, 6.5 of which are waterways... another possibility could be to inspect them, see if they are a good match for our styles, and clean up the geopackages contents removing what we don't need (e.g. the full process would be download + sql scripts). I'm downloading them to have a look, will update this ticket as I'm done.

**Comment by aaime** [comment]
Checked https://download.osmdata.xyz/, data layers are unsuitable, we need a single type attribute, the data instead has for each class a column, with a yes/no in it (so lots and lots of columns):

![image](https://user-images.githubusercontent.com/325433/74830883-60ff0b00-5314-11ea-8bb7-65f41ec43d13.png)

I guess this does it, we really need to work our way using imposm3 and thus download a full planet file...

**Comment by Gnafu** [comment]
Tests done on our namespace.
Waiting for Rosa to review the CI/CD pull request

**Comment by Gnafu** [comment]
Deployed, this can be closed
