### ISSUE TITLE
Serializer errors when using the Importer GUI

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/eumetsat-EOWS#193]
This is not impacting any functionality, but the error is logged.

JIRA issue: https://osgeo-org.atlassian.net/browse/GEOS-9438

**Comment by simboss** [comment]
@imranrajjad, usual steps.
Let's focus on the problem, you can ask more info to @Gnafu if needed to replicate.

This is a fix so it should go to all active branches.

**Comment by imranrajjad** [comment]
### Initial findings

I was able to re-produce the problem by following steps provided by @Gnafu . In the error message the Wicket framework is complaining about a non-serializable singlton bean of class  [org.geoserver.importer.Importer](https://github.com/geoserver/geoserver/blob/master/src/extension/importer/core/src/main/java/org/geoserver/importer/Importer.java), which is being referenced inside a submit button at [ImporterConfigPage](https://github.com/geoserver/geoserver/blob/master/src/extension/importer/web/src/main/java/org/geoserver/importer/web/ImporterConfigPage.java#L72). Since the wicket framework . As per my limited knowledge of Wicket, the whole page and workflow is serialized by the framework.

A simple solution to have the [org.geoserver.importer.Importer](https://github.com/geoserver/geoserver/blob/master/src/extension/importer/core/src/main/java/org/geoserver/importer/Importer.java) class implement **java.io.Serializable**, however this will only works on bean like classes encapsulating information whereas the **Importer** class holds other nested objects that cannot be serialized e.g [JobQueue.java](https://github.com/geoserver/geoserver/blob/master/src/extension/importer/core/src/main/java/org/geoserver/importer/job/JobQueue.java). This class holds contents that cannot be serialized.


### Possible solution

We can take advantage of the Singleton scope of **Importer** bean. To solve the serialization issue, we can access the bean inside the submit call back at [ImporterConfigPage()](https://github.com/geoserver/geoserver/blob/master/src/extension/importer/web/src/main/java/org/geoserver/importer/web/ImporterConfigPage.java#L72) . So the submit callback will look something like

```
Importer importerBean = getGeoServerApplication().getBeanOfType(Importer.class);
importerBean.setConfiguration(info);
```
The fix is subtle.

**Unit test** : The serialization error does not occur during the unit test, not sure about how to test the fix

Estimate : 1 hour

**Comment by aaime** [comment]
I agree with @imranrajjad proposal of looking up the importer dynamically.

**Comment by imranrajjad** [comment]
@aaime thanks, going ahead with implementation

**Comment by imranrajjad** [comment]
master: https://github.com/geoserver/geoserver/pull/3960

**Comment by imranrajjad** [comment]
@aaime PR looks good to be reviewed

**Comment by Gnafu** [comment]
This will need a backport to https://github.com/geosolutions-it/geoserver/tree/EOWS-158 too

**Comment by imranrajjad** [comment]
2.15.x?

**Comment by Gnafu** [comment]
No, it's a fork of 2.16.x
Needs a cherry pick

**Comment by imranrajjad** [comment]
https://github.com/geoserver/geoserver/pull/3994 this is the 2.16.x backport

**Comment by simboss** [comment]
@imranrajjad do you remember the repo and branch for the cherry pick?

**Comment by imranrajjad** [comment]
@simboss

 PR was ready but might require reabasing after travis fix

https://github.com/geosolutions-it/geoserver/pull/147

**Comment by simboss** [comment]
@Gnafu can you double check?

**Comment by Gnafu** [comment]
Travis build restarted, I'll review when finishes

**Comment by Gnafu** [comment]
merged
