### ISSUE TITLE
Support for legends

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/eumetsat-EOWS#200]
From Borgia:

Ho provato, negli ultimi due giorni, a fare la seguente cosa:
 1. Abbiamo un layer raster su GeoServer che va presentato cosi com’e’, senza applicare color scale o altro. Cosa che gia facciamo.
 2. Ho una leggenda pronta per questo layer, sia in PNG, che in SLD, e vorrei servirla come GetLegend, per questo layer. Ho letto sulla documentazione dei GeoServer che devo definire uno stile ad-hoc per questo layer, cosa che ho fatto, e definire li la leggenda, ma ho incontrato questi 2 problemi:
 - Se uso il PNG (nella definzione dello stile, posso specificare un’immagine, che ho messo nella directory degli stili di geoserver), allora nel GetCapabilites, per quel layer, non ho piu una chiamata a GetLegend, ma il link diretto a quella immagine, cosa che non va bene perche, per le nostre impostazioni di Apache, quella immagine non e’ direttamente accessibile.
 - Se uno l’SLD (vedi sotto per l’SLD), credo che GeoServer provi a re-applicare la color scale all’immagine, che ha gia la color scale applicata. Ne risulta che il layer non e’ corrrettamente visualizzato (non vedo proprio niente, se chiedo una preview del layer).
 La mia domanda e’: c’e’ un modo di specificare una leggenda, accessibile con GetLegend, per un layer, senza alterare l’aspetto del layer stesso? Non so se sono stato chiaro. Qui sotto, c’e’ l’SLD che ho usato.
``` 
 <?xml version="1.0"?>
 <StyledLayerDescriptor xmlns="http://www.opengis.net/sld" xmlns:ogc="http://www.opengis.net/ogc" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0.0" xsi:schemaLocation="http://www.opengis.net/sld StyledLayerDescriptor.xsd">
   <NamedLayer>
     <Name>METESOSAT STYLE CTH</Name>
     <UserStyle>
       <Title>METESOSAT STYLE CTH</Title>
       <FeatureTypeStyle>
         <Rule>
           <RasterSymbolizer>
             <Opacity>1.0</Opacity>
             <ColorMap type="ramp" extended="true">
               <ColorMapEntry color="#FFFFFF" quantity="16000" label="16000 m" />
               <ColorMapEntry color="#A0A0A0" quantity="14080" label="14080 m" />
               <ColorMapEntry color="#FE0000" quantity="12800" label="12800 m" />
               <ColorMapEntry color="#FFFF00" quantity="10240" label="10240 m" />
               <ColorMapEntry color="#00C000" quantity="7680" label="7680 m" />
               <ColorMapEntry color="#00FFFF" quantity="6400" label="6400 m" />
               <ColorMapEntry color="#0000FF" quantity="3840" label="3840 m" />
               <ColorMapEntry color="#C000C0" quantity="2560" label="2560 m" />
               <ColorMapEntry color="#672F00" quantity="1280" label="1280 m" />
               <ColorMapEntry color="#010000" quantity="320" label="320 m" />
              </ColorMap>
           </RasterSymbolizer>
         </Rule>
       </FeatureTypeStyle>
     </UserStyle>
   </NamedLayer>
 </StyledLayerDescriptor>
```

**Comment by simboss** [comment]
As usual, let's see an estimate and a plan.

**Comment by imranrajjad** [comment]
### Translated to English
From Borgia:

In the past two days I have tried to do the following:

1. We have a raster layer on GeoServer which must be presented as it is, without applying color scales or anything else. Which we already do.
2. I have a legend ready for this layer, both in PNG and in SLD, and I would like to serve it as GetLegend for this layer. I read in the GeoServer documentation that I have to define an ad-hoc style for this layer, which 

I did, and define the legend there, but I encountered these 2 problems:

- If I use PNG (in the style definition, I can specify an image, which I put in the geoserver styles directory), then in the GetCapabilites, for that layer, I no longer have a call to GetLegend, but the direct link to that image which is not a good thing because, for our Apache settings, that image is not directly accessible.
- If one is the SLD (see below for the SLD), I believe that GeoServer tries to re-apply the color scale to the image, which already has the color scale applied. As a result, the layer is not correctly displayed (I don't see anything, if I ask for a preview of the layer).


My question is: is there a way to specify a legend, accessible with GetLegend, for a layer, without altering the appearance of the layer itself? I do not know if I was clear. Below, there is the SLD that I used.

**Comment by simboss** [comment]
@imranrajjad additional information from Fabrizio Borgia:

> Actually, if we could specify a remote URL in the Legend section, it would be perfect, but I think our version of GeoServer is affected by this bug (there is an Andrea Aime post in the link):
> http://osgeo-org.1560.x6.nabble.com/Legend-remote-External-Graphic-td5393793.html

**Comment by simboss** [comment]
So we need to investigate the issues with the functionality to use a pre-cooked legend, list them and provide an estimate for the fix

The investigation shall take 1 couple of hours at most, if you need more, let me know.

**Comment by nmco** [comment]
@imranrajjad what we are referring too here is this functionality:
![image](https://user-images.githubusercontent.com/1590542/73652402-c8635c80-467e-11ea-9caf-7734b5b7e03f.png)

Although both the web UI and [documentation](https://docs.geoserver.org/stable/en/user/styling/webadmin/index.html) seems to imply that we can indeed use an HTTP location, that doesn't look like it's the case, because in the capabilities document we get the following:

```xml
<LegendURL width="800" height="637">
            <Format>image/png</Format>
            <OnlineResource xmlns:xlink="http://www.w3.org/1999/xlink" xlink:type="simple" xlink:href="http://cld-dev.emsa.geo-solutions.it/geoserver/styles/https://help.gaiagps.com/hc/article_attachments/360043198034/geologic-map-legend.png"/>
          </LegendURL>
```

The ``xlink:href`` is wrong, it concatenates the provided URL with he GeoServer base URL for the styles directory. This is seems to imply that the provided legend location needs to be relative to the GeoServer data directory styles directory.

So the minimum we need here is the possibility of defining the possibility of pointing to a legend (image) that comes form an HTTP(s) location, (is this correct @Gnafu?). Bare in mind @imranrajjad that the implemented fix needs t be backwards compatibility, it shoudl not break existing configurations.

**Comment by imranrajjad** [comment]
@nmco thanks for clarification..perhaps a checkbox saying : External, which if checked will not have anything pre-fixed.

**Comment by imranrajjad** [comment]
### Plan

A checkbox indicating that graphic is external needs to be added in [ExternalGraphicPanel](https://github.com/geoserver/geoserver/blob/master/src/web/wms/src/main/java/org/geoserver/wms/web/data/ExternalGraphicPanel.java) and then binded to a new model property called isExternal in  [LegendInfoImpl](https://github.com/geoserver/geoserver/blob/master/src/main/src/main/java/org/geoserver/catalog/impl/LegendInfoImpl.java).

For example

```
public boolean isExternal();
public void setExternal(boolean isExternal);
```

This property will be used to remove the warning on GUI and when writing a WMS  Capability document this property will be used to decide whether to append base url or not [GetCapabilitiesTransformer.handleLegendURL](https://github.com/geoserver/geoserver/blob/master/src/wms/src/main/java/org/geoserver/wms/capabilities/GetCapabilitiesTransformer.java#L1522)

Estimate : 1 day (implementation + unit tests + documentation)

**Comment by aaime** [comment]
Is the checkbox actually needed? The style URL should be recognizable as a string starting with http or https no?

**Comment by simboss** [comment]
@imranrajjad I was about to say what @aaime said.

I mean, we don't need a checkbox, I hope in 1day we can write code smart enough to recognize http or https as a URL protocol.
There should be a ton of code in GT/GS to do this (DataUtilities classes if I recall correctly).

@imranrajjad ?

**Comment by imranrajjad** [comment]
@simboss indeed a one liner in [GetCapabilitiesTransformer.handleLegendURL](https://github.com/geoserver/geoserver/blob/master/src/wms/src/main/java/org/geoserver/wms/capabilities/GetCapabilitiesTransformer.java#L1522) can fix this. The GUI part was suggested as UI sugar.

### Revised Plan

Base URL will not be prefixed for external legend URLs
(https://github.com/geoserver/geoserver/blob/master/src/wms/src/main/java/org/geoserver/wms/capabilities/GetCapabilitiesTransformer.java#L1522) . A unit test to assert the changes.

Estimate : 4 Hours (implementation + unit tests + documentation)

please let me know if I can move ahead with the improvment

**Comment by nmco** [comment]
@imranrajjad regarding this:
>  The GUI part was suggested as UI sugar.

Asking the user to provide information that you can easily infer is not _UI sugar_, so in practice this means that you will parse the URL and validate that the URL is and HTTP or HTTPS location? Since we are here did you also consider adding support for ``file://``?

@imranrajjad is not clear if you considered the following aspects:

- the current UI shows a warning saying that the URL needs  to be relative to the styles directory, this need to be updated
- did you double check that having a legend not local in the file system will work everywhere? a few points that come to my mind:
  - layer preview when configuring a style, the legend is displayed
  - when configuring a layer, selecting the default style, the legend is previewed

Can you update your plan mentioning the points above explicitly? Thank you.

@Gnafu for each version of GeoServer do we need this? 2.17.-RC and 2.16.3?

**Comment by simboss** [comment]
@nmco I think we can target master and backport right away as this is a fix of a functionality which is super broken right now.

**Comment by nmco** [comment]
@simboss I agree, @imranrajjad make sure that when you create the JIRA ticket you mark it has a BUG :wink:.

**Comment by Gnafu** [comment]
@nmco It's 2.16.x custom branch : https://github.com/geosolutions-it/geoserver/tree/EOWS-158

**Comment by simboss** [comment]
so we need to backport to 21.6.x and then to our custom branch.

**Comment by simboss** [comment]
@imranrajjad can you confirm the estimate and let us know when you are able to start?

**Comment by imranrajjad** [comment]
@simboss just going through some last minute checks, will share shortly

**Comment by imranrajjad** [comment]
@nmco 

- The preview functionality works with legend graphic url set to http/https
- Support for file:/ , I can definitely consider it
- The UI warning will be removed


@simboss 
### Revised Plan 2

To fix this bug, the following changes are proposed

#### Legend URL handling in capability document

[GetCapabilitiesTransformer.handleLegendURL](https://github.com/geoserver/geoserver/blob/master/src/wms/src/main/java/org/geoserver/wms/capabilities/GetCapabilitiesTransformer.java#L1522)

Currently for legend images inside style directory, the legend url is returnd as a direct path to the image file (as pointed by user). This method will be modified  such that legend Url will contain a GetLegendGraphic Url identifical to that of SLDs in any case. This will handle both scenarios pointed by client
- direct path to image file
- path wrongly pre-fixed with base url

It will be seamless for client requesting legend  through GetLegendGraphic request since GS will acquire the external graphic internally.


### GUI changes

[ExternalGraphicPanel](https://github.com/geoserver/geoserver/blob/master/src/web/wms/src/main/java/org/geoserver/wms/web/data/ExternalGraphicPanel.java) will only display error if the entered URL is invalid, allowing user to configure UR and a file stored locally outside data directory

Total estimate 6 hours (changes are subtle, however unit testing will be required for all scenarios)

**Comment by simboss** [comment]
I am happy with the plan and estimates, you can go ahead.

**Comment by imranrajjad** [comment]
JIRA : https://osgeo-org.atlassian.net/browse/GEOS-9489
master PR : https://github.com/geoserver/geoserver/pull/4033

**Comment by imranrajjad** [comment]
Jody does not look happy about the file:/// access

**Comment by nmco** [comment]
Is this still in progress? Looks to me you applied Jody changes, if that's the case please move to the review column. I just comment on the PR.

**Comment by imranrajjad** [comment]
not yet, I will shortly

**Comment by Gnafu** [comment]
@imranrajjad is there any update on this?

**Comment by imranrajjad** [comment]
@Gnafu waiting on Jody to accept changes

**Comment by simboss** [comment]
@imranrajjad keep pushing!

**Comment by nmco** [comment]
@imranrajjad master merged, please backport this to 2.16.x right away, and make also a PR against this branch https://github.com/geosolutions-it/geoserver/tree/EOWS-158 contributing this fix.

**Comment by imranrajjad** [comment]
@nmco ok, on it

**Comment by imranrajjad** [comment]
2.16.x backport https://github.com/geoserver/geoserver/pull/4072
EOWS-158 port : https://github.com/geosolutions-it/geoserver/pull/154

**Comment by nmco** [comment]
Thx @imranrajjad, merged :+1:, GeoServer wise we are good: https://osgeo-org.atlassian.net/browse/GEOS-9489.

@Gnafu I will let you follow up on the custom branch :smiley:.

**Comment by Gnafu** [comment]
Assigning to me for validation

**Comment by nmco** [comment]
Did you had a chance to validate this one @Gnafu ?

**Comment by Gnafu** [comment]
It's working with the custom EUMETSAT build.
