### ISSUE TITLE
NetCDF ImageMosaic store is 20x slower than simple NetCDF store

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/eumetsat-EOWS#24]
2 copies of the same NetCDF file have been published with the simple NetCDF store and the ImageMosaic one.

From each store we published the same layer, with the same configuration and styles.

From NetCDF store: http://cloudsdi.geo-solutions.it/geoserver/eumetsat/wms?service=WMS&version=1.1.0&request=GetMap&layers=eumetsat:test_sst&styles=&bbox=-68.0,19.5,-50.0,33.5&width=768&height=597&srs=EPSG:4326&format=application/openlayers

From ImageMosaic store: http://cloudsdi.geo-solutions.it/geoserver/eumetsat/wms?service=WMS&version=1.1.0&request=GetMap&layers=eumetsat:sea_surface_temperature_nc&styles=&bbox=-68.0,19.5,-50.0,33.5&width=768&height=597&srs=EPSG:4326&format=application/openlayers

Requests to the first one take around 500ms to complete, while the one to the second one take 8 to 20 seconds.

Details about the stores setup can be found in the [WIKI](https://github.com/geosolutions-it/eumetsat-EOWS/wiki/Data-setup)

**Comment by aaime** [comment]
Summary of my findings. When using a mosaic GranuleDescriptor creates a low level reader and sets its input, causing it to perform some inizialization.
In NetCDF it is expensive, in particular we hit some code that has been recently added by Niels (for variable aggregation) that scans and inits the coordinate axis.
The UCAR library for this particular NetCDF recognizes this variable as a coordinate axis (but Tools UI does not report it as one):

````
    double sst_time(time=1, lat=1600, lon=3600);
      :_FillValue = 0.0; // double
      :long_name = "pixel time";
      :units = "seconds since 1981-01-01 00:00:00";
      :_ChunkSizes = 1, 400, 900; // int
````

Initializing this beast is very much expensive, there are almost 6 million double values read and then converted one by one into a time (this is also inefficient in that the calls are stateless and 6 million GregorianCalendar objects are created).

The stand-alone NetCDF reader does not suffer from this problem because it keeps a single reader initialized only one time.

Possible approaches:
* Make the inizialitazion faster (in particular conversion from double to Date)
* See if we can avoid making the UCAR library recognize sst_time as a coordinate axis
* See if we can avoid the axis loading when passing "initMetadata" set to false
* Finally, can we cache the readers somehow?

**Comment by dromagnoli** [comment]
This part of the UCAR code is converting the sst_time to a CoordinateAxis:
https://github.com/Unidata/thredds/blob/5.0.0/cdm/src/main/java/ucar/nc2/dataset/conv/DefaultConvention.java#L140

The netcdf specification reports that Variables representing time must always explicitly include the units attribute and a time coordinate is identifiable from its units string alone.
http://cfconventions.org/cf-conventions/v1.6.0/cf-conventions.html#time-coordinate

So the sst_time is identified as a coordinate axis.
The old code was excluding that since it was only dealing with CoordinateAxis1D.

However, in order to parse time aggregation as part of https://osgeo-org.atlassian.net/browse/GEOT-5702, time CoordinateAxis greater than 1D are now supported and a new CoordinateAxisHelper has been setup to deal with that:
https://github.com/geotools/geotools/blob/master/modules/plugin/coverage-multidim/netcdf/src/main/java/org/geotools/imageio/netcdf/cv/CoordinateVariable.java#L112

The problem here is that CoordinateVariable is a 1600x3600 elements 2D variable instead of a few times aggregation.

**Comment by simboss** [comment]
Cool,
we need to discuss this internally, before taking any action on this.

**Comment by dromagnoli** [comment]
We can at least exclude coordinateAxis having > 2 dimensions (as in the sst_time case which is a time,lat,lon variable).

**Comment by simboss** [comment]
@dromagnoli can you like the GeoServer JIRA for this?

I would also open and link here an issue for an enhancement of performance.

**Comment by dromagnoli** [comment]
Related JIRA is https://osgeo-org.atlassian.net/browse/GEOT-5821

**Comment by dromagnoli** [comment]
Andrea's finding on ImageMosaic potential performance enhancement has been summarized in this JIRA:
https://osgeo-org.atlassian.net/browse/GEOT-5822

**Comment by dromagnoli** [comment]
@Gnafu let's see how things work once the updated GeoServer (containing that fix) is deployed.
If performances are better (with the fix we are avoiding to load ~6Million of doubles and convert them to dates) I'm wondering if we can consider closing this ticket and delegate the performance improvements JIRA to a new one

**Comment by Gnafu** [comment]
It works wonderfully

**Comment by dromagnoli** [comment]
Good. @simboss, should we close this ticket and let the performance improvements investigations an external topic?

**Comment by aaime** [comment]
@simboss echoing others, this ticket seems to be "done"
