### ISSUE TITLE
Ingest AMV NetCDF Data

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/eumetsat-EOWS#26]
Data is available on the AMV folder both on the FTP as well as on the bigdisk storage in the office.

We need to configure a NetCDF Store and do a windbarb style similar to the one we did for the vector data.

We might also want to create a style similar to the one of the U and V current layers for gliders on cloudsdi. Ask me for clarifications if needed.

**Comment by simboss** [comment]
We have received a NetCDF file that contains Atmospheric Motion Vectors data as U and V component.

We should ingest it into GeoServer and then create a windbarb style for it.

**Comment by dromagnoli** [comment]
NCDUMP for the AMV file:

  dimensions:
    lat = 540;
    lon = 1000;
.....................................
    float WIND_V(lat=540, lon=1000);
      :_FillValue = -999.0f; // float
      :long_name = "wind v";
      :units = "UNDEFINED";
    float WIND_U(lat=540, lon=1000);
      :_FillValue = -999.0f; // float
      :long_name = "wind u";
      :units = "UNDEFINED";

Note U and V have UNDEFINED units.

**Comment by simboss** [comment]
Is this a problem for us?

What this should be, M/S or Knots?

**Comment by dromagnoli** [comment]
WindBarbs are knot based "marker".... a short barb is 5 knots, a long barb is 10 knots, a pennant is 50 knots and so on, combined together.

The windbarb marker has a unit of measure parameter indicating the uom of the input value. The underlying machinery will do the conversion if needed (when NOT knots).

windbarbs://default(15)[kts] | 15 wind intensity with [kts] unit of measure
windbarbs://default(9)[m/s]| 9 wind intensity with [m/s] unit of measure

Therefore, we just need to know if the values in the NetCDF are m/s or knots or what else in order to setup the style accordingly.

**Comment by Gnafu** [comment]
I'll setup a style in m/s
We can easily change it later if necessary

**Comment by simboss** [comment]
I also added two styles to extract U and V with contrast stretch to be used by the front-end to generate a Windy-like visualization.

@Gnafu you might want to document that as well.

**Comment by Gnafu** [comment]
[Done](https://github.com/geosolutions-it/eumetsat-EOWS/wiki/Styles#separate-u-and-v-components-styles)

**Comment by Gnafu** [comment]
I also added a style similar to the vetor data one: amc_color_windbarbs
![2017-09-15_1226.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55fc437f80356d12003c764c/125516c66e82c728ace21e0d46bac4cb74cfd3f0c2b8ea7cf50fa2c26b0a65633b0ba92e7391a172fd17220056571ff8170e5847a8afdb2ba6b76f78835b5abbd57f4366846c4ff8e7df46f554f832815d84bfb68b49c0ed3922e6888f4a3b1e060ac4.png)
