### ISSUE TITLE
Check if GEOS-9481(wps-download) impacts our use case.

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/eumetsat-EOWS#298]
https://osgeo-org.atlassian.net/browse/GEOS-9481

**Comment by Gnafu** [comment]
@dromagnoli what is the actual effect of this issue?

We use the gs:Download process but we didn't find any issues as of today.

**Comment by dromagnoli** [comment]
The problem with that issue was that when asking for a wpsDownload on something different than byte (so, Int16, Float, Double,....) you was getting a rescaled to 8 bit version of data. As far as I remember this was only occurring when imposing a width and height to the target output image being downloaded, due to going through a different code path
