### ISSUE TITLE
Issue with font labels

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/eumetsat-EOWS#303]
@aaime has noticed that we might be missing some fonts on the EUM server.

Andrea will tell us more...

**Comment by aaime** [comment]
The map as rendered on maps.geo-solutions.it looks as follows, see the labels:

![image](https://user-images.githubusercontent.com/325433/76763468-77717880-6793-11ea-9869-54ff9e050c8e.png)

![image](https://user-images.githubusercontent.com/325433/76763502-86582b00-6793-11ea-97aa-dba1e6edf3e4.png)


In order to get there, the Noto fonts should be installed on the server:
https://www.google.com/get/noto/

**Comment by simboss** [comment]
@Gnafu this is for you!

**Comment by Gnafu** [comment]
Done.
Note for future self: fonts must be available at the root "fonts" directory, not in subfolders
