### ISSUE TITLE
Enabling Nearest Match makes GetTimeSeries fail

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/eumetsat-EOWS#319]
JIRA: https://osgeo-org.atlassian.net/browse/GEOS-9554

When Nearest Match is enabled, the GetTimeSeries fails with the following error:
```
Error processing the operation
org.geotools.util.DateRange cannot be cast to java.util.Date
```

**Comment by Gnafu** [comment]
JIRA: https://osgeo-org.atlassian.net/browse/GEOS-9554

**Comment by simboss** [comment]
@Gnafu can you prepare some sample data for this?

I am going to ask @taba90 to work on it.

**Comment by Gnafu** [comment]
Everything needed to reproduce this is in the JIRA description

**Comment by simboss** [comment]
@aaime can you do do an analysis on this one and put down some indications on how to fix this one?

**Comment by aaime** [comment]
The situation is a bit odd, it seems it was created this way, but without testing data that does not match due to search limits.

This method triggers the computation: https://github.com/geoserver/geoserver/blob/b76bba7178d3505cd45e318e659c3b32faee4b5e/src/community/ncwms/src/main/java/org/geoserver/wms/ncwms/NcWmsService.java#L82

and internally it ends up with the class cast exception because it's expecting a Date, but the nearest match code is returning the time being searched for (a range!) when it cannot match.
I believe there are multiple errors at play here, to match code should also match, 2019/2021 contains 2020, but the nearest code does not find it... yes, there is a bug here too:
https://github.com/geoserver/geoserver/blob/b76bba7178d3505cd45e318e659c3b32faee4b5e/src/main/src/main/java/org/geoserver/util/NearestMatchFinder.java#L193
This code should search first inside the range, and check what's lower and higher than it only if no matches are found inside.

So two bugs to fix:
- when searching nearest for a range, search first inside the range
- when no element is found or not close enough (which can be legit) don't just expect a Date object to be returned, while the matching code could return a range.

**Comment by simboss** [comment]
@aaime can you list the modules involved to test and fix this, just in case we have to pass this over to someone else.

**Comment by taba90** [comment]
Started work on this. Issue got reproduced.
According to what Andrea said
For the first bug fix I'm adding a between filter to check if date is in range before checking lowers and highers.
The second bug fix, seems to simply imply the adding of a filter operation to the stream before cast is performed;

**Comment by aaime** [comment]
For the second I would not be so sure... the code seems to extract dates to map back to date ranges... might as well just keep the date ranges if they show up.

**Comment by taba90** [comment]
Some things are not clear to me:
1) In this [method ](https://github.com/geoserver/geoserver/blob/master/src/community/ncwms/src/main/java/org/geoserver/wms/ncwms/NcWmsService.java#L245) it is stated that querying dates with a simple
range like the one at stake here (Case A in the method comment) we should have one result. I've tested this with an image mosaic store with two granules with different dates 
and with a simple date range comprising both. WIthout enabling the nearest match I get both the result, while enabling it and not passing an acceptable interval I will get one result. 
I'm then unable to understand what would be the correct behaviour ( I should get two or one result?). The [documentation ](https://docs.geoserver.org/latest/en/user/community/ncwms/index.html)seems to not tell nothing about this. The question, looks to me, is affecting also the current issue, because using a between filter before getting lower and higher in the nearest match finder, would imply that in the defined case I would get two results, so how should those be handled in the case that is true that a simple range should return a single result, and given the fact that [getNearest ](https://github.com/geoserver/geoserver/blob/master/src/main/src/main/java/org/geoserver/util/NearestMatchFinder.java#L168)Method seems designed to return one value? 
2) I guess I'm not understanding your point @aaime : for what I got, dates are mapped to DateRange, to get then only the min value and write it to the list of result in the csv or in the chart. Keeping the querying range and not filtering 
it out wouldn't imply to get the user fooled seeing the lower range limit as a date result?

**Comment by dromagnoli** [comment]
About your 1st point, NearestMatchFinder will return the closest value in a WMS request. So when specifying a range in a standard WMS call with NearestMatch enabled it will return the single value closest to that range.
Since an ncWMS GetTimeSeries is a specific operation aimed to get multiple times I think that for a request with a simple timeRange (neither a list of times, nor a START/END/PERIOD specification) it should go through the NearestMatchFinder only if the simple query will not return anything.
So based on your above example of 2 granules in a valid range, the getTimeSeries should return both in my opinion.
@aaime do you agree with that?

**Comment by aaime** [comment]
@dromagnoli yes, I agree.

**Comment by taba90** [comment]
According to last updates:

1. Instead of adding a between filter in the getMatches of the NearestMatchFinder, in [getNearestMatch ](https://github.com/geoserver/geoserver/blob/b76bba7178d3505cd45e318e659c3b32faee4b5e/src/community/ncwms/src/main/java/org/geoserver/wms/ncwms/NcWmsService.java#L245) method
in case that a simple time interval with no period is passed and nearest match is flagged a Query match will be performed before performing a Nearest match that would be invoked in the case in which no value is being retrieved.

2.  no values found by the nearest match finder will be ass well properly handled to avoid class cast exception.
estimated time is 3 hours

**Comment by taba90** [comment]
Pull request https://github.com/geoserver/geoserver/pull/4162

**Comment by simboss** [comment]
@taba90 make sure we backport to the branches where this applies and the cherry pick to EUM branch for @Gnafu to test

**Comment by nmco** [comment]
@taba90 looks like the PR was merged. since this is a bug fix, please backport to the branches where it applies and cherry pick to EUM has requested.

Remember to update the JIRA ticket, thank you.

**Comment by taba90** [comment]
thanks for the reminder, backports got merged and fix has been cherry-picked to EOWS branch too.

**Comment by Gnafu** [comment]
Confirmed working on "geoserver-dev" environment
