### ISSUE TITLE
Build EOWS-158 GeoServer branch on Jenkins

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/eumetsat-EOWS#325]
A continuous build is needed for this branch https://github.com/geosolutions-it/geoserver/tree/EOWS-158

Test should run at least on the following profiles:
authkey control-flow css feature-pregeneralized importer libjpeg-turbo monitor netcdf netcdf-out wps importer-jdbc ncwms ghrsst wmts-multi-dimensional wps-download wps-jdbc

**Comment by simboss** [comment]
This is a top priority.

**Comment by randomorder** [comment]
HI @Gnafu 
I set up a build [here](https://build.geo-solutions.it/jenkins/view/Eumetsat%20-%20EOWS/job/GeoServer%20EOWS-158)

The build is failing though. The are [test failure in the wms and wps modules](https://build.geo-solutions.it/jenkins/view/Eumetsat%20-%20EOWS/job/GeoServer%20EOWS-158/3/). Can we involve the developers to check the errors? Not sure who is the right person to ask for help, maybe @taba90?

**Comment by randomorder** [comment]
re-run the build today. We get a different error now
we probably need a dev to take a look @simboss

**Comment by simboss** [comment]
@taba90 can you double check what is going with the build?

This is preventing us from deploying the new fixes.

**Comment by taba90** [comment]
@simboss @randomorder 

- Failings on WPS-JDBC module are caused by missing property file for oracle and postgres in the 
 `{user directory}/.geoserver` . Those file are need to run live test on postgres and oracle. To set up 
 those file it is possible to follow the documentation regarding[ app-schema online test] 
 (https://docs.geoserver.org/latest/en/developer/programming-guide/app-schema/index.html), 
 having care of naming those file as wps-postgis.properties and wps-oracle.properties.

- Failings on Netcdf-ghrsst are caused by a missing dependency in the pom.xml; I've updated the 
  branch with the fix.

- Failing on wps-download is my fault, I've updated the branch with the fix;

- Failing on ncwms are caused by a test working on windows but failing on linux, this has been fixed too;

- Failing on wms module didn't get reproduced but it doesn't happears to show up everytime so looks like is simply random.

**Comment by randomorder** [comment]
Thank you @taba90 

> * Failings on WPS-JDBC module are caused by missing property file for oracle and postgres in the
>   `{user directory}/.geoserver` . Those file are need to run live test on postgres and oracle. To set up

Sorry, what's `user directory` ? and does this mean we need a running postgresql instance to build geoserver without skipping the tests?

**Comment by taba90** [comment]
Using windows I put the .geoserver dir under c:/Users/{user} so I guess on linux should be placed in /home/{user}, and this means that to completely run test a postgresql instance and an oracle one running are needed. I guess we can exclude them by modifying the pom of that specific module. if needed I can update it

**Comment by simboss** [comment]
@taba90 we should mimic for the moment what geoserver build server does and I believe it is _not_ running the tests for this modules as it is a community extension.

@Gnafu @randomorder next time when a developer prepare a custom branch he needs to be in the loop of the email failuers for it as he is requested to fix it timely.

**Comment by taba90** [comment]
wps-jdbc online test have been deactivated so now failings will not show up even if db properties files are not present. The build should be now be succesfull also with community module tests running

**Comment by simboss** [comment]
@taba90 I added you to the recipients for failures so you can see them.

We still have issues, can you double check?

**Comment by taba90** [comment]
@simboss @randomorder Seems a directory name with spacing issue. A test file is searched here `/opt/jenkins_home/workspace/**GeoServer%20EOWS-158**/src/web/wms/target/test-classes/org/geoserver/wms/web/data/GeoServer_75.png`  instead of `/opt/jenkins_home/workspace/GeoServer EOWS-158/src/web/wms/target/test-classes/org/geoserver/wms/web/data/GeoServer_75.png`

**Comment by simboss** [comment]
Strange that this not failing on the standard build.

Can you go ahead and fix it?

**Comment by taba90** [comment]
build is succesful

**Comment by simboss** [comment]
Can you elaborate a bit so that I do not have not ask again or dig for information? ;)

Is this something we should port on the community GeoServer?

**Comment by taba90** [comment]
Porting it to the community GeoServer will not hurt, I just modified a line in a test in order to not read directory with space replacing it with %20. But looks like the directory triggering the issue is specific to the environment where the build happens here `/opt/jenkins_home/workspace/GeoServer EOWS-158`
that's why the failure is not happening on standard build

**Comment by simboss** [comment]
@taba90 can you open an issue in GeoServer for this, assign it to you and link it here?

**Comment by taba90** [comment]
Here the ticket https://osgeo-org.atlassian.net/browse/GEOS-9612

**Comment by simboss** [comment]
@Gnafu feddback.

**Comment by Gnafu** [comment]
Pushed to gitlab and worked flawlessly.
