### ISSUE TITLE
Importer fails to init context with demo data

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/eumetsat-EOWS#328]
This is happening on Windows
https://osgeo-org.atlassian.net/browse/GEOS-9571

**Comment by taba90** [comment]
Not sure this is a bug. Even if the documentation in some point use the filename only to refer to granule in the task, in  the examples section full path is used (https://docs.geoserver.org/latest/en/user/extensions/importer/rest_examples.html). Indeed using a request body like this the import task gets correctly created:

{
  "import": {
    "targetStore": {
      "dataStore": {
        "name": "m"
      }
    },
    "data": {
        "type": "file",
        "file": "C:/marco_workspace/A/2.tif"
      },
    "targetWorkspace": {
      "workspace": {
        "name": "a"
      }
    }
  }
}

**Comment by nmco** [comment]
You feedback its not clear to me @taba90, is there a problem whit the documentation? Or wiht the request @Gnafu used?

**Comment by taba90** [comment]
@nmco I mean that in the documentation examples section full path is used in order to create import task and specifing a full path as file attribute indeed import creation works. What I mean is that it looks like this is the intended way of create import tasks through the rest interface since in the examples section of documentation is used always a full path

**Comment by nmco** [comment]
@taba90 I don't have time to look into the details of every issue, so what's going on here:
- The request describe on the JIRA ticket its wrong?
- The GeoServer documentation its wrong?

What do we need actually to do here?

**Comment by simboss** [comment]
@Gnafu can you check this discussion?

**Comment by taba90** [comment]
@nmco I think there is no bug here, since according documentation example section full path is used and with a full path a new context is correctly created eg using a json body like this one:

{
"import": {
"targetStore": {
"dataStore": {
"name": "m"
}
},
"data": {
"type": "file",
"file": "C:/marco_workspace/A/2.tif"
},
"targetWorkspace": {
"workspace": {
"name": "a"
}
}
}
}

**Comment by Gnafu** [comment]
This means that we can import files that are referenced by the full path.
Sounds reasonable.

Not a bug, we can convert this to a feature request if necessary.
