### ISSUE TITLE
Importer logs incorrectly when workspace is wrong

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/eumetsat-EOWS#329]
![image.png](https://images.zenhubusercontent.com/5cd44174fe59e12f2130c49d/7f88f661-a8d5-4571-96fe-2ddff920beec)

Fix here: https://github.com/geoserver/geoserver/commit/3610e4885bfba08440d7d2290adb4b9b5b7a8228

**Comment by nmco** [comment]
@taba90 can you estimate this one?

**Comment by taba90** [comment]
simply needs to correct this line https://github.com/geoserver/geoserver/blob/45b6d5ed2a1961493b7faf9c5e6d6c5693a559b9/src/extension/importer/rest/src/main/java/org/geoserver/importer/rest/ImportController.java#L193. Is a simple update that I think can be made in the context of fix for https://github.com/geosolutions-it/eumetsat-eows/issues/327 since is the same class and almost the same code section

**Comment by Gnafu** [comment]
@taba90 @nmco I already opened a JIRA: https://osgeo-org.atlassian.net/browse/GEOS-9572
And sent a pull request for this: https://github.com/geoserver/geoserver/pull/4182
You can just review it and maybe improve it if you want.

**Comment by Gnafu** [comment]
We only need a backport of https://github.com/geoserver/geoserver/pull/4182 to our custom geoserver branch
