### ISSUE TITLE
GEOS-6888 Importer Tasks errors are not logged

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/eumetsat-EOWS#331]
https://osgeo-org.atlassian.net/browse/GEOS-6888

**Comment by nmco** [comment]
Is this related with #329? @taba90 can you try to reprodcue and estimate?

**Comment by taba90** [comment]
This issues seems to not be related. I guess to ticket is point toward to add logging  instead of simply throw a rest exception in Controllers' class present in the module. The are also few catch block that are not logging anything. I think that one hour should be enough to add log where exception are thrown. I'm also relying on the fact that adding logs would not imply new tests am I wrong?

**Comment by nmco** [comment]
@taba90 looks reasonable to me, and indeed adding logs doesn't require tests.

**Comment by taba90** [comment]
Master pull request https://github.com/geoserver/geoserver/pull/4188
