### ISSUE TITLE
[WMS-OPE-GUI-1321] Improve legends in downloads

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/eumetsat-EOWS#359]
From the client:

> The user shall be able to download images and animations featuring an overlay showing the legend of one or more included visualizations. The user shall be able to choose the list of legends to be displayed.
The current implementation of EUMETView disables the basemap when adding the legend overlay. This was not requested, we would like the user to choose to display the basemap or not, just like he/she does during the regular (without overlay) image download.

Let's discuss this and put together a potential ballpark estimate with a plan.

**Comment by simboss** [comment]
waiting for more details...

**Comment by nmco** [comment]
For reference, legends are displayed on the ``mp4`` videos that can be export from EUMESAT portal, legends inclusion need to be activated explicitly, not all layers have a legend defined. Behind the scenes the portal uses GeoServer ``wps-dowload`` plug-in to export the video and associated legend [through a ``gs:DownloadMap`` WPS process invocation.](https://github.com/geoserver/geoserver/blob/master/src/community/wps-download/src/test/resources/org/geoserver/wps/gs/download/mapSingleLayerWithLegendDecoration.xml#L20-L25)

Although [this is not currently documented](https://docs.geoserver.org/stable/en/user/community/wps-download/mapAnimationDownload.html#decoration-layout) (something to improve), the legend (and any other decoration) will only be included [if a single layer is requested](https://github.com/geoserver/geoserver/blob/master/src/community/wps-download/src/main/java/org/geoserver/wps/gs/download/DownloadMapProcess.java#L325). 

The portal should be able to export maps containing a base layer and _data_ layer, including the legend for the later. Fixing this will require:

- Extending the current [``gs:DownloadMap`` WPS process](https://github.com/geoserver/geoserver/blob/master/src/community/wps-download/src/test/resources/org/geoserver/wps/gs/download/mapSingleLayerWithLegendDecoration.xml#L20-L25) to allow the invoker to define the layer for which the legend should be included. If no layer is explicitly defined for the legend, then the current behaviour should be applied. 
- Unlike WMS requests where decorations are applied using all layers, the [``gs:DownloadMap`` WPS process injects the layout to apply per layer](https://github.com/geoserver/geoserver/blob/master/src/community/wps-download/src/main/java/org/geoserver/wps/gs/download/DownloadMapProcess.java#L326-L331), hence we only need to make sure to inject the layout for the needed layer only (basically changing the if condition).

The estimate for this fix is 8 hours.

This portion _The user shall be able to choose the list of legends to be displayed._ of the user request is not covered by this fix.

**Comment by simboss** [comment]
Latest feedback from the client.

`The user shall be able to download images and animations featuring an overlay showing the legend of one or more included visualizations. The user shall be able to choose the list of legends to be displayed, up to a maximum of 2.`

Shalle we update the estimate? A Obviously they need it right away.

**Comment by nmco** [comment]
Yes we need to update the estimate to 16 hours, my suggestion is too extend the WPS process to receive a list of layers, like it already does, and as well a list of decorations (an empty space means that no decoration will be done for that layer), something like this:
```xml
<wps:Execute version="1.0.0" service="WPS"
    (...)
    <wps:Input>
      <ows:Identifier>decoration</ows:Identifier>
      <wps:Data>
        <wps:LiteralData>layout1,layout2</wps:LiteralData>
      </wps:Data>
    </wps:Input>
   (...)
    <wps:Input>
      <ows:Identifier>layer</ows:Identifier>
      <wps:Data>
        <wps:ComplexData xmlns:dwn="http://geoserver.org/wps/download">
          <dwn:Layer>
            <dwn:Name>tiger:tiger_roads,tiger:poly_landmarks</dwn:Name>
          </dwn:Layer>
        </wps:ComplexData>
      </wps:Data>
    </wps:Input>
  </wps:DataInputs>
  (...)
```

The map produced for the input above will look like this (notice the two legends):
![image](https://user-images.githubusercontent.com/1590542/92606934-6e2d1880-f2ab-11ea-8952-2311d78f95ef.png)

This solution means that the client will be able to:
- Define different layouts, for example, positing the legend in different locations.
- Decide which layers will have the legend draw and where, by combining the `layers` and `decoration` inputs parameters as needed. 

The drawback of this solution, is that we will need to do an extra rendering for each decoration, hence the download will be a bit slower.

**Comment by nmco** [comment]
Taking into account the new requirements, which are not clear, e.g., what does this means?:_We would like the legends to be in a dedicated area of the image (in a bar at the top)._ Do they want the legend to not overlap the map? ... Anyway, whit a very high uncertainty I would push this to 5 / 8 days of work. **To reduce the high risk, a mock of what they want should be created and and proper plan \ estimation done.**

**Comment by simboss** [comment]
I will go for 6 given the amount of time we have asked in the past.

**Comment by simboss** [comment]
@nmco we have a green light to move forward with this.

The client wants to have this in prod before Christmas. Taking into account that we have to deploy and test in DEV and then in PROD, we need this ready to be deployed by November 30th the latest, which means the change has been backported and cherrypicked to the EUM branch.

**Comment by simboss** [comment]
@nmco let's discuss this on Tue as I need to have it ready by end of November.

**Comment by nmco** [comment]
@jemacchi the client and project codes are::

EUMETSAT - CGI | C068-EUMETSAT-CGI-2019-WP1
-- | --

@jemacchi let's start by reading the requirements above, prepare your questions and draft a plan, then let's have a meeting to decide how to move forward.

**Comment by jemacchi** [comment]
@nmco 

**Estimation:**
2 days  (check assumptions/consideration notes)

**Considerations/Assumptions:**
-  estimation is not including changes on WMS Decorations framework. It includes only changes in the WPS process that allows to get decorations applied.

Regarding WPS:
- decoration input (xml definition) wont be changed to cast to List at execute method (line 124, DownloadMapProcess.java) since that would affect previous versions behavior.
- when layers are listed independently as wps:Input in the request, then it wont be possible to match order between decoration input (as a list of decorators) and a layer. Matching only work when layer input arrives in a format on which  dwn:Name is a list of layers separated by comma.
- If decorationName is a list of decorators, then match 1st decorator with 1st layer, and so on.
- If we have more than one layer, decorationName is not null and we have only 1 decorator defined (size=1), then apply the same decorator for all the layers.
- Optional: If decorationName is a list of decorators that does not match with the size of layers -> throw error ?  (that would change previous defined behavior. No changes on estimation)

Regarding Decorations definitions for type="legend":
- "...bar at the top..." mentioned by client implies that legends are defined at top of the generated image with affinity="top" on decoration/layout definition.
- questions related to size of legends should point the customer to use layout definition parameters (ie. change size="auto")
- in general, customer requests related to set layout of legends are handled at decorator definition level, but changes like styling to apply as part of the background for the legend area, it's not part of current decoration xml set of attributes in the framework)
- in order to estimate this part of work, @nmco I need your assistance on how to extend decorators framework.

**Actions:**
- modify [buildImage method](https://github.com/geoserver/geoserver/blob/6bdf573f2499e802c8bca036c63502a6e9a469b5/src/community/wps-download/src/main/java/org/geoserver/wps/gs/download/DownloadMapProcess.java#L276) (class DownloadMapProcess.java) to capture list of all layers and match them with decorator (based on index order) to apply one by one on each layer. Based on considerations, it's only required to change code on that method (in particular adapting code in this [for block](https://github.com/geoserver/geoserver/blob/6bdf573f2499e802c8bca036c63502a6e9a469b5/src/community/wps-download/src/main/java/org/geoserver/wps/gs/download/DownloadMapProcess.java#L326))
- build tests for different cases using decoration input as a list of separated decorators (with one or more layers)

**Comment by nmco** [comment]
Meeting minutes with @jemacchi  16 of November 2020:
- Functional requirements:
  - The client wants to be able to download a map /(in this case with will be an animation displaying meteo satellite data) that contains the base layer and the imagery layer with a legend for both.
  - The base map and the selected layer (imagery) should be displayed, currently if multiple layer are requested (for example a base layer and the imagery layer) decorations are dropped.
  - The client wants also the possibility to display multiple legends and select the layers for which the legends will be displayed:
     - If the client download a map with 20 layers I doubt we can locate 20 legends, we will not support aggregation ro that type of stuff.
  - The client wants the legend to be grouped on the top bar with a custom background color.
  - They also want the possibility of defining the size legend size relative to the image size.
  - Ideally the client doesn't want this options to be hard-coded in the decoration definition, but hey will.
- This issue will become an epic and sub issue will be created for each functional requirement.

**Comment by simboss** [comment]
@nmco @jemacchi keep an eye on the time budget, please.

That said, let me know if you need some sample data. It might not be super easy to set that up though, we might need @randomorder help as these are imagemosaics. I think this is crucial to avoid wasting time aftewards.

**Comment by nmco** [comment]
@jemacchi make sure you check the new comments on the sub issues. We need to document [here](https://docs.google.com/document/d/1QF8ZfsL9F5-ZkniV_rvPzDPfGLEeiA-dXGQ9AO8Wjdo/edit#heading=h.tx9u7z3610ps) (Max 1 page) how the new API look like and the generated map, make sure you use print-screens and screenshots from EUMETSAT portal.

This is the document that will be shared with the client it needs to be crystal clear for them how the API and the final image will look like, they will start updating their client to match the API we will mention here, hence we can't chnage it.

Since the functional requirements are not clear at all, this is what we are assuming:
- The client wants mock 3, which implies that we will respected the requested image size, but we will need to shrink the map to fic the size + adding the top grey bar.
- Max two legend can be requested, but multiple layers can be requested.
- Ideally the size of the top bar should be controlable whit some relative resizing.

Make sure you review the estimate on each sub issue, thx!

**Comment by nmco** [comment]
@simboss you can find [here](https://docs.google.com/document/d/1QF8ZfsL9F5-ZkniV_rvPzDPfGLEeiA-dXGQ9AO8Wjdo/edit#heading=h.qo0xkt1jy78l) the plan for implementation. The estimate to implement waht's described on the document is 4 days. 19 hours were already spend on the planning.

**Comment by nmco** [comment]
For reference:
- Adding the top gray bar was estimated to 4 days.
- Adding the resizing of legends (with the available interpolations, low quality) 1.5 days.

**Comment by jemacchi** [comment]
@simboss @randomorder @nmco 

Final document on how to use/setup improvements [here](https://docs.google.com/document/d/1Fe39M7jLZQKUXaAE2cY_sHvtsPqcZgt989qRUeMR-I0)

**Comment by randomorder** [comment]
can you check this made it all the way to OPE @jemacchi ? https://view.eumetsat.int/

**Comment by jemacchi** [comment]
> can you check this made it all the way to OPE @jemacchi ? https://view.eumetsat.int/

@randomorder  I have checked it in prod, but it seems that latest updates on layout files are not there (I'm referring to this [issue](https://github.com/geosolutions-it/eumetsat-EOWS/issues/458) ).  
This is current result from a map download (for a couple of layers). It seems that issue 485 is still pending to be applied (you can see that header it's still not covering 100% of width).

![Eumetsat_view_2021-01-18T1430](https://user-images.githubusercontent.com/1171099/104936219-fa9ec480-598a-11eb-9083-7d448bc97f4e.png)

**Comment by simboss** [comment]
@jemacchi bug them view JIRA and email if needed.
Please, take responsibility to have this reach production properly...

**Comment by jemacchi** [comment]
@simboss @randomorder  
I have created a ticket in [JIRA](https://cgi-pathfinders.atlassian.net/browse/W9-36). 
Based on your comments @randomorder I added the link to commit that should fix the issue (so they can track that it's still pending for deployment).
Please let me know if you find things I should consider when creating such kind of tickets (ie. codes naming conventions, etc)

**Comment by simboss** [comment]
This is still in dev!

**Comment by jemacchi** [comment]
@simboss  laste week @randomorder pushed for some info. Today I did the same. Feature is in DEV, ready for VAL.
