### ISSUE TITLE
ImageMosaic initialization improvements on source check

### ISSUE THREAD

**Issue by dromagnoli** [geosolutions-it/eumetsat-EOWS#366]
See details on https://osgeo-org.atlassian.net/browse/GEOT-6693

Long story short:
- try avoiding the directory scan when looking for property files (directory can contains thousands of files)
- only support directory or specific config files on input

**Comment by simboss** [comment]
@dromagnoli we deployed this and it appears to be running properly.

However, I think there are still corner cases where we are listing things too much, see [this](http://demo.geo-solutions.it/share/test/09_08_2020/jstack2) jstack.

So if we follow the flow, we are havesting a file and not a directory since we go through this line of code

[org.geotools.gce.imagemosaic.ImageMosaicReader$HarvestedResource$1.harvest(ImageMosaicReader.java:205)(https://github.com/geosolutions-it/geotools/blob/b537116aed14fd762e8e44d9745ab81a948ae270/modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/ImageMosaicReader.java#L205)

however, this lead to the walker to run even if this is a single file, see the following line in the jstack:
org.geotools.gce.imagemosaic.ImageMosaicReader$HarvestedResource.harvestCalculation(ImageMosaicReader.java:436)


Infact we find ourselves in [this](https://github.com/geosolutions-it/geotools/blob/b537116aed14fd762e8e44d9745ab81a948ae270/modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/ImageMosaicDirectoryWalker.java#L185) code in the ImageMosaicDirectoryWalker which loops through the files in the directory again even if we are trying to scan a single file.

**Comment by simboss** [comment]
I think this makes sense; a couple of things:

- make sure there is no other place where we unecessarily loop through the directory
- I would probably go down the path of creating an ImageMosaicWalker implementation that is inizialized with a list of files as an alternative to **always** scanning a directory. I mean the implementation of the harvesting capability should have already gone down this path.
-  I would probably open a issue to move away from common utils and use plain java methods (see [here](https://stackabuse.com/java-list-files-in-a-directory/)).

Please, prepare a plan and an estimate.

**Comment by dromagnoli** [comment]
In relation to the original issue on performing a File scan during initialization there are several cases to be taken into account:

- Mosaic has a single coverage: 99% of the times, the coverage name has the same name of the mosaic config folder -> no scan needed
- 1% of old mosaics have a default mosaic.properties file -> no scan needed
- Multidimensional coverages (i.e NetCDF mosaics) have an ABC.properties file for each different coverage (temperature.properties, ozone.properties, wind.properties).  We can parse the indexer.xml, gathering coverage names and look for those coveragename.properties file -> no scan needed
- Multi coverages mosaic built on coverage names collector use some regex to extract the coverage name from the file name, i.e. when representing different bands as different coverages. i.e. B1.tif, B2.tif, B3.tif, .... There is no way to know in advance the name of these coverages and therefore the name of these properties files due to the "dynamic" nature of the naming, based on the actual directory content -> scan is still needed OR we need to store the coveragenames list on an additional file?

**Comment by dromagnoli** [comment]
Closing this ticket after having isolated the multicoverage initialization topic on its own ticket:
https://github.com/geosolutions-it/eumetsat-eows/issues/375
