### ISSUE TITLE
Timeliness issues with the EUMETView Ng ingestion

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/eumetsat-EOWS#378]
See issue [IMGMT-379](https://cgi-pathfinders.atlassian.net/browse/IMGMT-379).

Daniele has provided a code fix for this which we should deploy asap on DEV, test and then move to prod.
The issues related to the fix are:
- #366 (imageMosaic source check initialization)
- #374 (single file harvest triggering a directory scan anyway)
- #376 (Importer triggering a directory scan when looking for supplemental files)
The code is already on our fork.

I also suggested to create subdirectories during ingestion (ask duty) so that dirs are small.

**Comment by randomorder** [comment]
I am about to deploy in DEV

**Comment by randomorder** [comment]
Deployed in DEV moving to OPE for final testing

**Comment by randomorder** [comment]
From Fabrizio Borgia:

"Hi Simone Giannecchini ,

I totally agree about the change of approach with the Shapefile ingestion - since the GeoServer and the ingestion pods share a storage partition, i think it would be possible to just reference the shapefile, rather than posting it. I will discuss with the team and let you know. In general, I can say that we are very happy with the ingestion times right now, I think the fix really made the difference. For the moment, if you agree, i think we can close this issue, and we will create new ones for future enhancements."
