### ISSUE TITLE
IMGMT-396 - Security Anomaly: Stack Traces leak Information

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/eumetsat-EOWS#385]
This ticket summarizes findings where stack traces leak information about the underlying software. This is usually an indicator that error reporting is too verbose. The following list enumerates all findings that were made throughout this pentest:

URLs that cause stack traces:
https://view.eumetsat.int/geoserver/gwc/rest/web/ EXT

While this is not a vulnerability per se, stack traces can aid attackers in gaining intel about the underlying software and architecture and plan exploitation of services more accurately. It should be made sure that detailed error reporting should be turned off for each of the URLs in the list above.

**Comment by simboss** [comment]
If I make a request to [https://view.eumetsat.int/geoserver/gwc/rest/](https://view.eumetsat.int/geoserver/gwc/rest/) I get a 403 as I would expect but the response above does not look right to me.

This is raising concerns as a result of penetration testing hence this might require fixing on our side.
@aaime do you think this is something we can improve at the GWC level? Can you throw us an estimate?

**Comment by aaime** [comment]
Multiple things going on here:

* The exception comes from monitoring, it should be made more tolerant to requests it does not understand:
```
org.geoserver.monitor.MonitorFilter.doFilter(MonitorFilter.java:193)
	org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:66)
	org.geoserver.flow.controller.IpBlacklistFilter.doFilter(IpBlacklistFilter.java:89)
```

* Hitting the same URL locally, with the monitoring on, it does not happen... maybe it has already been made more tolerant, or some other plugin is involved (do we have GeoFence in the mix? it messes up with the setup of REST interfaces)

* Even hitting something entirely different, I still cannot get the same result locally... and I believe this is actually Tomcat displaying the exception by default, if it happens to hit it, instead of being managed by the local application. See here, "Disable Client Facing Stack traces": https://blogs.mulesoft.com/dev/tomcat-tcat-server/is-your-tomcat-secure/
and also here, https://tomcat.apache.org/tomcat-9.0-doc/security-howto.html, search for "The default ErrorReportValve"

**Comment by simboss** [comment]
Conclusion is, we fix it with devops expertise.

**Comment by randomorder** [comment]
Submitted MR to configure ErrorValve. Waiting for merge to test in DEV

**Comment by randomorder** [comment]
validated and queued for relase

**Comment by randomorder** [comment]
deployed on OPE
