### ISSUE TITLE
Support decorations with multiple layers in downloads

### ISSUE THREAD

**Issue by nmco** [geosolutions-it/eumetsat-EOWS#402]
For reference, legends are displayed on the ``mp4`` videos that can be export from EUMESAT portal, legends inclusion need to be activated explicitly, not all layers have a legend defined. Behind the scenes the portal uses GeoServer ``wps-dowload`` plug-in to export the video and associated legend [through a ``gs:DownloadMap`` WPS process invocation.](https://github.com/geoserver/geoserver/blob/master/src/community/wps-download/src/test/resources/org/geoserver/wps/gs/download/mapSingleLayerWithLegendDecoration.xml#L20-L25)

Although [this is not currently documented](https://docs.geoserver.org/stable/en/user/community/wps-download/mapAnimationDownload.html#decoration-layout) (something to improve), the legend (and any other decoration) will only be included [if a single layer is requested](https://github.com/geoserver/geoserver/blob/master/src/community/wps-download/src/main/java/org/geoserver/wps/gs/download/DownloadMapProcess.java#L325). 

The portal should be able to export maps containing a base layer and _data_ layer, including the legend for the later. Fixing this will require:

- Extending the current [``gs:DownloadMap`` WPS process](https://github.com/geoserver/geoserver/blob/master/src/community/wps-download/src/test/resources/org/geoserver/wps/gs/download/mapSingleLayerWithLegendDecoration.xml#L20-L25) to allow the invoker to define the layer for which the legend should be included. If no layer is explicitly defined for the legend, then the current behaviour should be applied. 
- Unlike WMS requests where decorations are applied using all layers, the [``gs:DownloadMap`` WPS process injects the layout to apply per layer](https://github.com/geoserver/geoserver/blob/master/src/community/wps-download/src/main/java/org/geoserver/wps/gs/download/DownloadMapProcess.java#L326-L331), hence we only need to make sure to inject the layout for the needed layer only (basically changing the if condition).

Top of the head suggestion is to extend the WPS process to receive a list of layers, like it already does, and as well a list of decorations (an empty space means that no decoration will be done for that layer), something like this:
```xml
<wps:Execute version="1.0.0" service="WPS"
    (...)
    <wps:Input>
      <ows:Identifier>decoration</ows:Identifier>
      <wps:Data>
        <wps:LiteralData>layout1,layout2</wps:LiteralData>
      </wps:Data>
    </wps:Input>
   (...)
    <wps:Input>
      <ows:Identifier>layer</ows:Identifier>
      <wps:Data>
        <wps:ComplexData xmlns:dwn="http://geoserver.org/wps/download">
          <dwn:Layer>
            <dwn:Name>tiger:tiger_roads,tiger:poly_landmarks</dwn:Name>
          </dwn:Layer>
        </wps:ComplexData>
      </wps:Data>
    </wps:Input>
  </wps:DataInputs>
  (...)
```

The map produced for the input above will look like this (notice the two legends):
![image](https://user-images.githubusercontent.com/1590542/92606934-6e2d1880-f2ab-11ea-8952-2311d78f95ef.png)

This solution means that the client will be able to:
- Define different layouts, for example, positing the legend in different locations.
- Decide which layers will have the legend draw and where, by combining the `layers` and `decoration` inputs parameters as needed. 

The drawback of this solution, is that we will need to do an extra rendering for each decoration, hence the download will be a bit slower.

**Comment by jemacchi** [comment]
Proposed solution implies:

- Adding a new tag dwn:DecoratorName in [Layer parametricEntity](https://github.com/geoserver/geoserver/blob/master/src/community/wps-download/src/main/java/org/geoserver/wps/gs/download/Layer.java )

Considerations:
  - that would allow to match a layer Name with a DecoratorName, so each layer can identify the decorator to be applied in a simple way.
  - then modify [buildImage method](https://github.com/geoserver/geoserver/blob/6bdf573f2499e802c8bca036c63502a6e9a469b5/src/community/wps-download/src/main/java/org/geoserver/wps/gs/download/DownloadMapProcess.java#L276) , to get name of decorator for each [Layer](https://github.com/geoserver/geoserver/blob/master/src/community/wps-download/src/main/java/org/geoserver/wps/gs/download/Layer.java)  layer entity and apply the decorator.
 - since we are not removing/changing meaning of any of other wps:Input, we keep compatibility with existing users definitions
 - when using a definition of multiple layers in a   <ows:Identifier>layer</ows:Identifier>, then order of names are used to match layers and decorators pairs.
 - those users that start to add the dwn:DecoratorName in the wps process call will get profit of the decoration based on each layer.

  - example of  `<ows:Identifier>layer</ows:Identifier>` with more than 1 layer defined:

```xml
<wps:Execute version="1.0.0" service="WPS"
   (...)
    <wps:Input>
      <ows:Identifier>layer</ows:Identifier>
      <wps:Data>
        <wps:ComplexData xmlns:dwn="http://geoserver.org/wps/download">
          <dwn:Layer>
            <dwn:Name>tiger:tiger_roads,tiger:poly_landmarks</dwn:Name>
            <dwn:DecoratorName>layout1,layout2</dwn:Name>
          </dwn:Layer>
        </wps:ComplexData>
      </wps:Data>
    </wps:Input>
  </wps:DataInputs>
  (...)
```

- example of `<ows:Identifier>layer</ows:Identifier>` with 1 layer defined:

```xml
<wps:Execute version="1.0.0" service="WPS"
   (...)
    <wps:Input>
      <ows:Identifier>layer</ows:Identifier>
      <wps:Data>
        <wps:ComplexData xmlns:dwn="http://geoserver.org/wps/download">
          <dwn:Layer>
            <dwn:Name>tiger:tiger_roads,</dwn:Name>
            <dwn:DecoratorName>layout1</dwn:Name>
          </dwn:Layer>
        </wps:ComplexData>
      </wps:Data>
    </wps:Input>
  </wps:DataInputs>
  (...)
```

- additionally, it would be possible to use multiple single `<ows:Identifier>layer</ows:Identifier>` definitions, since decorators are applied based on internal Name and DecoratorName options, as follow:

```xml
<wps:Execute version="1.0.0" service="WPS"
   (...)
    <wps:Input>
      <ows:Identifier>layer</ows:Identifier>
      <wps:Data>
        <wps:ComplexData xmlns:dwn="http://geoserver.org/wps/download">
          <dwn:Layer>
            <dwn:Name>tiger:tiger_roads,</dwn:Name>
            <dwn:DecoratorName>layout1</dwn:Name>
          </dwn:Layer>
        </wps:ComplexData>
      </wps:Data>
    </wps:Input>
    (...)
    <wps:Input>
      <ows:Identifier>layer</ows:Identifier>
      <wps:Data>
        <wps:ComplexData xmlns:dwn="http://geoserver.org/wps/download">
          <dwn:Layer>
            <dwn:Name>tiger:poly_landmarks</dwn:Name>
            <dwn:DecoratorName>layout2</dwn:Name>
          </dwn:Layer>
        </wps:ComplexData>
      </wps:Data>
    </wps:Input>
  </wps:DataInputs>
  (...)
```
- finally, when  `<ows:Identifier>decoration</ows:Identifier>`  is declared (that is current implementation), in order to keep compatibility, it will be expected to have layer definition without  dwn:DecoratorName defined (if not, tthen DecoratorName will be prioritized over the user of values defined in <ows:Identifier>decoration</ows:Identifier>.
That is, for this case on which we have:

```xml
<wps:Execute version="1.0.0" service="WPS"
   (...)
   <wps:Input>
      <ows:Identifier>decoration</ows:Identifier>
      <wps:Data>
        <wps:LiteralData>layout1</wps:LiteralData>
      </wps:Data>
    </wps:Input>
   (...)
    <wps:Input>
      <ows:Identifier>layer</ows:Identifier>
      <wps:Data>
        <wps:ComplexData xmlns:dwn="http://geoserver.org/wps/download">
          <dwn:Layer>
            <dwn:Name>tiger:tiger_roads,</dwn:Name>
            <dwn:DecoratorName>layout2</dwn:Name>
          </dwn:Layer>
        </wps:ComplexData>
      </wps:Data>
    </wps:Input>
    (...)
  </wps:DataInputs>
  (...)
```
DecoratorName = layout2 will be prioritized event when  layout1 is defined and we have only 1 layer in the WPS call.

**Comment by nmco** [comment]
Quick comments:
- Estimates missing.
- Supporting both is quite confusing, but indeed we can just get ride of backwards compatibility.

**Comment by jemacchi** [comment]
@nmco

Estimate:  2 days

Regarding supporting both, I think that it's the only way that will allow current users to work as it's now (in future, probably we can set that as a deprecated version? not sure how usually you handle that)

**Comment by nmco** [comment]
We can move on wiht this one @Jose.

**Comment by jemacchi** [comment]
@nmco  @aaime  @simboss 

I want to share status, since I'm now working on an improvement (planning that) for LegendDecorators, since each LegendDecorator is applied when each map is created, and are not stacked into the produced image at the end of process.

This is currently an output (Eumetsat dataset test) for 2 raster layers (on which we expect to have legends at top) + some vectorial layers (boundaries) + a decorator (that is not a legend type decorator) applied  at bottom.

![Captura de pantalla de 2020-11-20 12-40-01](https://user-images.githubusercontent.com/1171099/99818927-951a8d00-2b2d-11eb-9fce-3da0e1882d49.png)

As you can observe legends for both raster layers were applied and styled (gray transparent background) but unfortunatelly each LegendDecorator is applied when each map is requested, so when merging images, legends are overlaped with top map result (you can see that legend at left is overlaped with map rendered after, which shows its legend at right)
For purposes of testing, I have added a Decorator type = scaleline and a Decorator= Image, in a layout that is used and rendered at the end of process on top of all created map images, with an empty map request.

**Problem recap: each legend is added to each map image, then overlap could happen. A layout can be painted at end of process, but it's useful only for "non-related-to-legends" decorators.**

Now, trying to figure it out some alternative to avoid that overlap on legends.

**Comment by nmco** [comment]
Meeting minutes 20-11-2020:
- First all requested layer should be draw, and then only the decorators, like it is done for [the footer](https://github.com/geoserver/geoserver/blob/master/src/community/wps-download/src/main/java/org/geoserver/wps/gs/download/DownloadMapProcess.java#L365-L380). Otherwise they will overlap each other.
- Legends require a layer to be provided to the map content, we just need to make it possible to tell the rederign engine to draw everything except the layer itself, and basically only de decorator will be draw.

**Comment by simboss** [comment]
@jemacchi feedback from our client, I'd like to hear what you think about it.

> Hi Simone,
> thanks for the new preview, this is definitely the spatial organization that we like. We had a quick check with our user representatives, and we would like to have the following (chromatic changes).
> 
> Top bar background: RGB(251,251,251).
> Legend background: solid (not transparent) RGB(230,230,230).
> 
> Also, if possible, could you please harmonize the background of the footer to be RGB(251,251,251) too?
> 
> And one last optional request: which font is used for the timestamp at the bottom? For the legends, I used Roboto, would it be possible to see how it would look in the footer too?

I think this is just about changing colors in the decorator, but still...

**Comment by jemacchi** [comment]
@simboss  yes, it's all about styles that we can change. Let me bring you an output with that.

**Comment by jemacchi** [comment]
@simboss 
This is the result applying those changes (note: for Roboto, it's required font installed in the JVM. Rest of items are covered with changes on xml files or jpg/png resources used in backgrounds)

![response-newstyles](https://user-images.githubusercontent.com/1171099/100239111-c4efd900-2f0f-11eb-8c5d-218ebfa64ec6.png)

**Comment by randomorder** [comment]
this has been validated and is going to be released https://cgi-pathfinders.atlassian.net/browse/W9-36
