### ISSUE TITLE
Cached tiles in MapCache are always stored as PNGs

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/eumetsat-EOWS#450]
We have the format set to PNG at the moment so all tiles are stored on disk as PNGs (much heavier) and looks like the end user is always getting PNGs even when asking for format jpeg-png which in some cases should return jpeg encoded images.

Let's take the chance to check what happens with jpeg-png8 too. Not clear whether MapCache is also re-encoding the tiles every time before storing them on disk and the effect this may have on the final tile both interms of size and visual difference (palette). 

https://mapserver.org/mapcache/formats.html#mixed-format

> There is a third special format which mixes JPEG and PNG compression depending on the contents of the image. This format allows creation of caches for raster imagery using JPEG compression (which is more efficient) on zones with imagery data, and PNG compression (which supports transparency) on zones with no imagery or on a boundary between imagery and emptiness.

Complete docs [here](https://mapserver.org/mapcache/config.html#format)

**Comment by simboss** [comment]
I would introduce the ability to use JPEG + PNG using by default 32 bits PNGs.
I would introduce 256 color PNGs on a few selected layers of choice to show EUM the difference then they can extend this to other layers themselves.

**Comment by jemacchi** [comment]
@randomorder  
I found that your mapcache config tailored to a couple of layers set in local env is working as expected (no major changes on that) so I want to review the cache folder (where mapcache is saving files) in dev environment. Can yu assist me on that (basically because I need some help with the k8s stuff).

With a command such as  **file $(find .) | grep -E "JPEG|PNG"** we can see if it's saving or not jpeg and/or pngs.
In my case, I'm applying a watch to the local folder, and I got this result (it's working).

![image](https://user-images.githubusercontent.com/1171099/102808205-c097ce00-439e-11eb-85c9-7d76b087a87a.png)

**Comment by jemacchi** [comment]
@randomorder 
Since in local environment it worked, then as we discussed in chat, I tried in development environment.

What I see is that requests coming from [Eumetsat client ](https://view.cgi-dev.de/productviewer?v=default) for a known public layer (msg_fes:h03b) which result would be png or jpeg depending on behavior are not captured/handled by mapcache when defining parameter format=image/vnd.jpeg-png 

If instead of that, I change the request with format image/png or image/jpg, then no matter the specified format in the request, mapcache will capture the request and will response with the tile in the format based on MIXED logic (that is: if the image contains any transparency then it will be saved as png and if it does not contain any transparency it will be saved as jpg)

Resume: calls from client with format=image/vnd.jpeg-png are not recognized/captured by mapcache, hence it's not applying any login on them.

Here you have 2 requests that allow to test it:
Partial
https://view.cgi-dev.de/geoserver/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fvnd.jpeg-png&TRANSPARENT=true&LAYERS=msg_fes%3Ah03b&STYLES=&tiled=true&TIME=2020-04-02T17%3A00%3A00.000Z&WIDTH=512&HEIGHT=512&CRS=EPSG%3A4326&BBOX=-2.8125%2C5.625%2C0%2C8.4375

Full
https://view.cgi-dev.de/geoserver/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fvnd.jpeg-png&TRANSPARENT=true&LAYERS=msg_fes%3Ah03b&STYLES=&tiled=true&TIME=2020-04-02T17%3A00%3A00.000Z&WIDTH=512&HEIGHT=512&CRS=EPSG%3A4326&BBOX=-5.625%2C18.28125%2C-4.21875%2C19.6875

Note: reason locally it worked it's cause on my local client, format is not defined as image/vnd.jpeg-png

Not sure if this is something that Frontend team will have to consider or not (since I dont know really if mapcache understand that kind of format). Anyway, I cannot test more than that for today since servers are down (exactly 6 PM my time, they are shutdown)

**Comment by randomorder** [comment]
We want to avoid changing the image format in the request. Check the documentation and google around to see what other people are doing

**Comment by randomorder** [comment]
ignore my previous comment. Let's wrap this up and ask the client to use image/png for all Publicly available layers

Only thing left to is test png8 format and seee the effect on tile size and visual difference on a subset of layers @jemacchi
Of course we want to try this on layers that have a wide dynamic range and great variety of shades of colours

For instance:
- msg_fes:rgb_airmass
- copernicus:daily_sentinel3ab_olci_l1_rgb_fulres
- eps:m03_rgb_124
- msg_iodc:rgb_ash
- msg_iodc:rgb_natural
- msg_fes:wv062

**Comment by jemacchi** [comment]
@randomorder  please check results below (those samples provides an idea of what is happening regarding quality and size)

### CASE msg_fes:rgb_airmass

**From Mapcache (as client is doing):**

![msg_fes-rgb_airmass-mapcache-png8](https://user-images.githubusercontent.com/1171099/104056619-8e280680-51cf-11eb-845f-8ccd5864ac31.png)

_PNG8 - 31.4kb - 512x512_
https://view.cgi-dev.de/geoserver/wms?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&FORMAT=image%2Fpng8&TRANSPARENT=true&tiled=true&LAYERS=msg_fes%3Argb_airmass&exceptions=application%2Fvnd.ogc.se_inimage&tilesOrigin=-77%2C-77&WIDTH=512&HEIGHT=512&SRS=EPSG%3A4326&STYLES=&BBOX=-22.5%2C16.875%2C-16.875%2C22.5

![msg_fes-rgb_airmass-mapcache](https://user-images.githubusercontent.com/1171099/104056662-9d0eb900-51cf-11eb-816d-3d83f6158c21.jpeg)

_JPEG-PNG - 27.0kb - 512x512   (saved as JPEG, handled by Mapcache)_
https://view.cgi-dev.de/geoserver/wms?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&FORMAT=image%2Fvnd.jpeg-png&TRANSPARENT=true&tiled=true&LAYERS=msg_fes%3Argb_airmass&exceptions=application%2Fvnd.ogc.se_inimage&tilesOrigin=-77%2C-77&WIDTH=512&HEIGHT=512&SRS=EPSG%3A4326&STYLES=&BBOX=-22.5%2C16.875%2C-16.875%2C22.5


**From Geoserver master:**

![msg_fes-rgb_airmass-geoserver master-pngfull](https://user-images.githubusercontent.com/1171099/104056733-b57ed380-51cf-11eb-8ff9-e8a77b93b3ee.png)

_PNG full - 72.3kb - 512x512_
https://view.cgi-dev.de/geoserver-master/msg_fes/wms?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&tiled=true&LAYERS=msg_fes%3Argb_airmass&exceptions=application%2Fvnd.ogc.se_inimage&tilesOrigin=-77%2C-77&WIDTH=512&HEIGHT=512&SRS=EPSG%3A4326&STYLES=&BBOX=-22.5%2C16.875%2C-16.875%2C22.5

![msg_fes-rgb_airmass-geoserver master-png8](https://user-images.githubusercontent.com/1171099/104056747-badc1e00-51cf-11eb-83fb-157e7ff0d917.png)

_PNG8 - 31.4kb - 512x512_
https://view.cgi-dev.de/geoserver-master/msg_fes/wms?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&tiled=true&LAYERS=msg_fes%3Argb_airmass&exceptions=application%2Fvnd.ogc.se_inimage&tilesOrigin=-77%2C-77&WIDTH=512&HEIGHT=512&SRS=EPSG%3A4326&STYLES=&BBOX=-22.5%2C16.875%2C-16.875%2C22.5

![msg_fes-rgb_airmass-geoserver master-jpeg](https://user-images.githubusercontent.com/1171099/104056757-c0396880-51cf-11eb-88bb-a20365d28e3f.jpeg)

_JPEG - 28.1kb - 512x512_
https://view.cgi-dev.de/geoserver-master/msg_fes/wms?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&FORMAT=image%2Fjpeg&TRANSPARENT=true&tiled=true&LAYERS=msg_fes%3Argb_airmass&exceptions=application%2Fvnd.ogc.se_inimage&tilesOrigin=-77%2C-77&WIDTH=512&HEIGHT=512&SRS=EPSG%3A4326&STYLES=&BBOX=-22.5%2C16.875%2C-16.875%2C22.5


Note: notice that JPEG handled by Mapcache is smaller than JPG from Geoserver, since it's applying own transformations based on mapcache definition (quality defined in 75%)


### CASE msg_iodc:rgb_natural
**From Mapcache (as client is doing):**

![msg_iodc-rgb_natural-mapcache-png8](https://user-images.githubusercontent.com/1171099/104056799-d21b0b80-51cf-11eb-8220-e6a3cd3c4a20.png)

_PNG8 - 191kb - 512x512_
https://view.cgi-dev.de/geoserver/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng8&TRANSPARENT=true&LAYERS=msg_iodc%3Argb_natural&STYLES=&tiled=true&TIME=2020-02-17T07%3A45%3A00.000Z&WIDTH=512&HEIGHT=512&CRS=EPSG%3A4326&BBOX=22.5%2C22.5%2C45%2C45

![msg_iodc-rgb_natural-mapcache](https://user-images.githubusercontent.com/1171099/104056835-dfd09100-51cf-11eb-9a74-eda2e6ffe600.jpeg)

_JPEG-PNG - 47.7kb - 512x512   (saved as JPEG, handled by Mapcache)_
https://view.cgi-dev.de/geoserver/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fvnd.jpeg-png&TRANSPARENT=true&LAYERS=msg_iodc%3Argb_natural&STYLES=&tiled=true&TIME=2020-02-17T07%3A45%3A00.000Z&WIDTH=512&HEIGHT=512&CRS=EPSG%3A4326&BBOX=22.5%2C22.5%2C45%2C45

**From Geoserver master:**

![msg_iodc-rgb_natural-geoserver master-pngfull](https://user-images.githubusercontent.com/1171099/104056842-e232eb00-51cf-11eb-8836-08069ccd8389.png)

_PNG full - 594kb - 512x512_
https://view.cgi-dev.de/geoserver-master/msg_iodc/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=msg_iodc%3Argb_natural&STYLES=&tiled=true&TIME=2020-02-17T07%3A45%3A00.000Z&WIDTH=512&HEIGHT=512&CRS=EPSG%3A4326&BBOX=22.5%2C22.5%2C45%2C45

![msg_iodc-rgb_natural-geoserver master-png8](https://user-images.githubusercontent.com/1171099/104056852-e5c67200-51cf-11eb-9dda-5fb5426c2901.png)

_PNG8 - 191kb - 512x512_
https://view.cgi-dev.de/geoserver-master/msg_iodc/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng8&TRANSPARENT=true&LAYERS=msg_iodc%3Argb_natural&STYLES=&tiled=true&TIME=2020-02-17T07%3A45%3A00.000Z&WIDTH=512&HEIGHT=512&CRS=EPSG%3A4326&BBOX=22.5%2C22.5%2C45%2C45

![msg_iodc-rgb_natural-geoserver master-jpeg](https://user-images.githubusercontent.com/1171099/104056876-f0810700-51cf-11eb-9721-f972efa366c7.jpeg)

_JPEG - 49.7kb - 512x512_
https://view.cgi-dev.de/geoserver-master/msg_iodc/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fjpeg&TRANSPARENT=true&LAYERS=msg_iodc%3Argb_natural&STYLES=&tiled=true&TIME=2020-02-17T07%3A45%3A00.000Z&WIDTH=512&HEIGHT=512&CRS=EPSG%3A4326&BBOX=22.5%2C22.5%2C45%2C45

Note: again, Mapcache compression is allowing to get a better size in JPEG format


### Some conclusions:
- In attached images you can see the difference on quality between PNG8 and a full PNG (PNG24). With PNG8 it's clear that it's loosing quality (but improving size)
- Size for that kind of images (full, no transparences) is very well handled with JPG format, and so Mapcache is doing a good job when selecting which format to keep in order to provide good quaility and lower size.

**Comment by jemacchi** [comment]
@randomorder find attached 2 images comparing airmass (in context of a "border", since we want to compare PNG encoding between png8 and png full, and when MIXED is enabled for Mapcache then it's always returning a JPG file)

That is I basically tested getting PNGs directly from Mapcache.
Result: 
- Quality difference is noticed only on those tiles on which a wide colors/palettes are used (if not, differences are really almost invisible).
- Size between images (png8 and full png) are really noticed (png 8 is 50% smaller than full png ones. Note: it will depend also on the % of transparence)

Check below:

- Images compared (clean comparasion)
![Captura de pantalla de 2021-01-11 15-47-03](https://user-images.githubusercontent.com/1171099/104225906-c88ae100-5425-11eb-94a1-1383f359f7dc.png)

- Observed details regarding quality
![Captura de pantalla de 2021-01-11 15-51-11](https://user-images.githubusercontent.com/1171099/104225941-d2acdf80-5425-11eb-9687-363ded2642c6.png)

- Original images

PNG8, 23kb
![pngfull-airmass-from-dev-png8](https://user-images.githubusercontent.com/1171099/104226044-f7a15280-5425-11eb-835d-a655c13727be.png)

Full PNG, 56kb
![pngfull-airmass-from-dev-fullpng](https://user-images.githubusercontent.com/1171099/104226104-0ab42280-5426-11eb-9337-b610c2f1063f.png)

**Comment by randomorder** [comment]
Airmass looks good enough to me. @jemacchi let's wrap this up and submit 2 Merge Requests:
1 - for the adoption of the MIXED format using regular PNGs for all layers 
2 - additive to MR#1 that changes the configuration for Airmass to use PNG8. We'll eventually adopt it for more layers in the future
https://gitlab.cgi-dev.de/eows/wms/helm-charts/blob/master/charts/wms-geoserver/configFiles/mapcache.xml

**Comment by jemacchi** [comment]
@randomorder 
> 1 - for the adoption of the MIXED format using regular PNGs for all layers

MR step 1.   https://gitlab.cgi-dev.de/eows/wms/helm-charts/merge_requests/14

**Comment by jemacchi** [comment]
@randomorder 
For step 2, reference is https://gitlab.cgi-dev.de/eows/wms/helm-charts/merge_requests/14/commits  (the 2nd commit)
Let me know if MRs in this way are ok for you.

**Comment by randomorder** [comment]
Please subit 2 separate MRs if possible @jemacchi 

We want to allow for 2 distinct merge actions and 2 validations.

The reasoning behind this is, should Eumetsat reject png8 for airmass, we are still able to roll out the mixed format for mapcache.

**Comment by jemacchi** [comment]
@randomorder done !  For PNG8 we have a different branch and so a different MR (additive to step 1 branch)

https://gitlab.cgi-dev.de/eows/wms/helm-charts/merge_requests/15

**Comment by randomorder** [comment]
https://cgi-pathfinders.atlassian.net/browse/W9-42

**Comment by randomorder** [comment]
We also going to need a MR for the client config @jemacchi to use PNG from the client application
by changing this file https://gitlab.cgi-dev.de/eows/wms/wms-ui/blob/development/assets/data/productDecorations.json

Remember, **only** for the layers that are cached in mapcache, not for all layers

**Comment by jemacchi** [comment]
> We also going to need a MR for the client config @jemacchi to use PNG from the client application
> by changing this file https://gitlab.cgi-dev.de/eows/wms/wms-ui/blob/development/assets/data/productDecorations.json
> 
> Remember, **only** for the layers that are cached in mapcache, not for all layers

@randomorder  [MR](https://gitlab.cgi-dev.de/eows/wms/wms-ui/merge_requests/48) created and attached to this [ticket](https://cgi-pathfinders.atlassian.net/browse/W9-42)

**Comment by randomorder** [comment]
@jemacchi @simboss 
Merged the work for MapCache mixed format and manually updated the web client configuration (I don't have the grants to merge, I asked earlier today).

We can test now in DEV but the k8s cluster will be shut down in ~1hr I am afraid :(

Note: ATM Airmass is the only one stored as 8 bit PNG this is Not visible from the GetMap req where image format is always "png" . 8bit vs 24bit is set on the server side in the mapcache configuration.

**Comment by simboss** [comment]
@jemacchi I tried to test this today with @randomorder but apparently the config is gone.
Please, when you start do a timeboxed investigation (max 1h) to understand what happened.
Check the [deploy pipeline](https://gitlab.cgi-dev.de/eows/wms/helm-charts/pipelines) and what happens when they shut down machines, then come back with your investigation.

In any case, if the pipeline route takes time (i.e. more than 2 hours) to fix, deploy and test the fix manually (remember to clean old mapache cache).
I want to be able to see the airmass tiles for the edges as 8 bits PNGS today, if possible.

**Comment by jemacchi** [comment]
@randomorder @simboss 
Found it. In dev the  k8s configmap  was pointing to mapcache-cm instead of mapcache-config. Changed it in the statefulset for mapcache and restarted and it's now getting the config for PNG8 in Airmass.
(hint: hitting a tile, downloading it and running "file tile.png" should point you to a "PNG image data, 512 x 512, 8-bit colormap, non-interlaced" result, where 8-bit colormap is = PNG8)

**Comment by jemacchi** [comment]
@simboss I was looking at the JPEG result issue while calling backgrounds:ne_background layers (we were getting png instead of jpeg), and I think that what we saw in call (while you shared screen) it was the behavior in production environment ( https://view.eumetsat.int/productviewer?v=default ). wrong env. 

**In development environment, behavior is working good.**

**Notes:**
That is: background (baselayers) images are called with format = image/jpeg and the result is a jpeg file (attached image)

![dev-formatjpeg-background-resultjpeg](https://user-images.githubusercontent.com/1171099/105757159-63a6af00-5f2c-11eb-91fd-bb2a9fb983b2.png)

I checked wms-ui code, and discovered that BaseLayers are ALWAYS called with a jpeg format (check screen capture of code)

![baselayers-alwaysjpeg](https://user-images.githubusercontent.com/1171099/105757179-6acdbd00-5f2c-11eb-8e33-5b72aa57f264.png)


The layers that we define as MIXED in Mapcache are handled with following logic:
- WMS calls are always format=image/png   (that is because we defined the client to call image/png avoiding vnd.jpeg-png since we know that mapcache does not understand that).
- Mapcache captures the request and if it contains any transparent area (not full filled image) then will return a PNG (or PNG8 if set in that way, as for the case of airmass)
- If the image is full, then returns a jpeg.
- No matter if the WMS call use a format=image/jpeg, Mapcache will consider the encoding based on the transparency (resulting in a jpeg or png).

I have also checked background images (in dev) and despite you could set format=image/png (manually, since wms-ui code does not allows you), Mapcache is returning a  JPEG file (using logic described before).
**Short story long: if the layer is set with MIXED format in Mapcache, no matter what format you use (image/jpeg or image/png) the returning file will depend on the opacity/transparency of the content.**

So far, I think that today when we reviewed in call we were looking at the wrong environment. 
Besides that, I cheched in production, and I can see that currently even when format = image/jpeg  for the background images, the resulting image is a png (but I cannot access production config files in order to check why it's happening that).

ie in prod:  https://view.eumetsat.int/geoserver/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fjpeg&TRANSPARENT=true&LAYERS=backgrounds%3Ane_background&STYLES=&tiled=true&WIDTH=512&HEIGHT=512&CRS=EPSG%3A4326&BBOX=22.5%2C-45%2C45%2C-22.5

that call retrieves a PNG despite it's asking for a jpeg

same request pointing to development returns a JPEG  (no matter if you ask for jpeg or png)
https://view.cgi-dev.de/geoserver/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fjpeg&TRANSPARENT=true&LAYERS=backgrounds%3Ane_background&STYLES=&tiled=true&WIDTH=512&HEIGHT=512&CRS=EPSG%3A4326&BBOX=22.5%2C-45%2C45%2C-22.5

**Comment by simboss** [comment]
@jemacchi long story short, yes we were looking at the wrong environment.

That said, in dev if you check the requests to the overlays layer (see in the TOC the **Overlays** item and subitems) are being served by GWC rathern than MapCache.
This means they are missing form the configuration of MapCache that @lpasquali put together, I presume. Please, open a separate issue and investigate.
This means we might need another MR to update the conf.

**Comment by jemacchi** [comment]
@simboss  @randomorder  @lpasquali 

> That said, in dev if you check the requests to the overlays layer (see in the TOC the **Overlays** item and subitems) are being served by GWC rathern than MapCache.

Yes, and that is because overlays layers are hardcoded to call WMS with format=image/png8.  Since MC does not recognize the png8 as a format, then is sending it to the geoserver behind it.
Below section of code in WMS-UI that is doing that

![image](https://user-images.githubusercontent.com/1171099/105765532-57741f00-5f37-11eb-9bab-8db3e4eba180.png)

note: something similar happen with baselayers (those are set as jpeg, no way to modify that unless a change on client code is done)

**Comment by randomorder** [comment]
moving to test and waiting for validation by eumetsat

**Comment by randomorder** [comment]
This is still waiting for testing from CGI https://cgi-pathfinders.atlassian.net/browse/W9-42
