### ISSUE TITLE
Issue with GeoTiff and No Data #1

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/eumetsat-EOWS#460]
**Original GeoTiff** [here](https://www.dropbox.com/s/av66cw7kqdkc7sz/WideAreaCoverage_RGBNatColour_PlateCarree_2011010000.tif?dl=0).
**Optimized GeoTiff** [here](https://www.dropbox.com/s/785sdb99itokdff/WideAreaCoverage_RGBNatColour_PlateCarree_2011010000_opt.tif?dl=0).
**Optimizations steps** as follows:
* gdal_translate -co COMPRESS=DEFLATE -co TILED=YES -co BLOCKXSIZE=512 -co BLOCKYSIZE=512 -mo "NODATA_VALUES 0 0 0" WideAreaCoverage_RGBNatColour_PlateCarree_2011010000.tif WideAreaCoverage_RGBNatColour_PlateCarree_2011010000_opt_bilinear.tif
* gdaladdo -r bilinear --config COMPRESS_OVERVIEW DEFLATE  --config GDAL_TIFF_OVR_BLOCKSIZE 512 WideAreaCoverage_RGBNatColour_PlateCarree_2011010000_opt_bilinear.tif

**Issue**
Strange artifacts (see video attached) appear at different resolution levels, which looks NODATA management issues. 
Disabling map wrapping does not help.
Notice that we forced in the metadata (0,0,0) as nodata triplet so what is happening here is strange.

I would expect that bilinear turns some nearblack pixels to black during overviews creation hence they are therefore treated as nodata, but what I see here is not consistent and it happens more and more as I zoom in (which means as I gets close to using original data).
![eum-issue](https://user-images.githubusercontent.com/693880/104821286-0e3b1580-583b-11eb-834f-52c3f4767447.gif)

**Comment by dromagnoli** [comment]
@simboss 

Checking the metadata once processed with that command I have noticed that the NODATA_VALUES metadata was not applied.
So I have just spotted bad syntax.

the metadata part should be:
-mo NODATA_VALUES="0 0 0"
(notice the = sign for the assignment).

whilst the used command isn't properly setting the value.
I have tested locally and I don't see these weird rendering.
Could you please retry with that?

I will check the 2nd ticket too but I suspect the problem is the same
