### ISSUE TITLE
Add New Collections / Layers to Web Client

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/eumetsat-EOWS#462]
Understand how to and add new collections and layers to Eumetview.

Pointers to config files by Cesare Rossi here: https://cgi-pathfinders.atlassian.net/browse/W9-39

DRAFT Document to expand and complete [here](https://docs.google.com/document/d/1VPCjq2B3mKowwjHxntZXsT8q9YXUsZTlN143V3moI38/edit)

**Comment by randomorder** [comment]
What we want to achieve here is understand and document how to perform the task @jemacchi 

Check the ticker in description and ask questions in the ticket to address what is unclear.

**Comment by jemacchi** [comment]
> DRAFT Document to expand and complete [here](https://docs.google.com/document/d/1VPCjq2B3mKowwjHxntZXsT8q9YXUsZTlN143V3moI38/edit)

@randomorder   can you share doc with me ?

**Comment by jemacchi** [comment]
@randomorder  I followed instructions in the [Draft Doc](https://docs.google.com/document/d/1VPCjq2B3mKowwjHxntZXsT8q9YXUsZTlN143V3moI38/edit) in order to apply changes based on this [issue](https://github.com/geosolutions-it/eumetsat-EOWS/issues/450#issuecomment-763541818) 

For layers configuration edition document it's clear enough.
For some other configuration tasks mentioned [here](https://cgi-pathfinders.atlassian.net/browse/W9-39) I think that probably we should add a section mentioning the related files (I'll add a couple of sections in draft document)

**Comment by jemacchi** [comment]
@randomorder added some samples in [documentation](https://docs.google.com/document/d/1VPCjq2B3mKowwjHxntZXsT8q9YXUsZTlN143V3moI38/edit#heading=h.hpvkr3wxmvs0).

Moving issue for review.

**Comment by randomorder** [comment]
Please check my comments and add the following two layers as requested by @simboss 
- mumi:wideareacoverage_rgbnatcolour	
- mumi:wideareacoverage_rgb_natural_jpeg

**Comment by jemacchi** [comment]
> * mumi:wideareacoverage_rgbnatcolour
> * mumi:wideareacoverage_rgb_natural_jpeg

@randomorder  
about those 2 layers:
- i can see them in geoserver master DEV (but disabled)
- do you know the wms-ui code I should use ? (basically EO:EUM:DAT:somethinghere , but need some reference about naming conventions if required)
- should I add them in the mapcache config too ? 
- last, there is a difference on name for the rgbnatural layer (at least in dev env)

![image](https://user-images.githubusercontent.com/1171099/105377415-8c0b7200-5be9-11eb-8971-f4a9f89e650c.png)

let me know if we should fix/rename it.

**Comment by randomorder** [comment]
> > * mumi:wideareacoverage_rgbnatcolour
> > * mumi:wideareacoverage_rgb_natural_jpeg
> 
> @randomorder
> about those 2 layers:
> 
> * i can see them in geoserver master DEV (but disabled)
> * do you know the wms-ui code I should use ? (basically EO:EUM:DAT:somethinghere , but need some reference about naming conventions if required)

That's what I am asking in the GDoc and is part od the assignement of this issue :)
You should ask [here](https://cgi-pathfinders.atlassian.net/browse/W9-39)
In the meantime try to put some example values and see if it works

> * should I add them in the mapcache config too ?

Yes please, these are free layers AFAIK

> * last, there is a difference on name for the rgbnatural layer (at least in dev env)
> 
> ![image](https://user-images.githubusercontent.com/1171099/105377415-8c0b7200-5be9-11eb-8971-f4a9f89e650c.png)
> 
> let me know if we should fix/rename it.

Check the spreadsheet. If not availble in the spreadsheet use the name reported in geoserver

**Comment by jemacchi** [comment]
> That's what I am asking in the GDoc and is part od the assignement of this issue :)
> You should ask [here](https://cgi-pathfinders.atlassian.net/browse/W9-39)

done (question in doc and also reviewed spreadsheet)

There is a difference between layers names in spreadsheet and geoserver/mapcache files as you can see below (so I'm adjusting spreadsheet to match defined in geoserver)

Original spreadsheet:
![image](https://user-images.githubusercontent.com/1171099/105401631-2f1db500-5c05-11eb-9e8f-c43a8d7b7379.png)

Geoserver (in DEV):

![image](https://user-images.githubusercontent.com/1171099/105401866-6a1fe880-5c05-11eb-80f2-afd9ce26064b.png)


FYI, in column F of [spreadsheet](https://docs.google.com/spreadsheets/d/1i2gLyWd6SPYSWDj_OWh3mjGhh3Px-md0/edit#gid=420042348) you can see the codes that should be used (so I will add them to the related json file)

**Comment by jemacchi** [comment]
@randomorder  some other stuff. Despite this mumi:wideareacoverage_rgb_natural_jpeg layer exists in Geoserver dev environment, it's not part of the [spreadsheet](https://docs.google.com/spreadsheets/d/1i2gLyWd6SPYSWDj_OWh3mjGhh3Px-md0/edit#gid=420042348)  and there are no codes for it.

Also added a question for Cesare about adding a new layer, and how that it reflects in the Product Search dialog, since the called endpoint (https://api.cgi-dev.de/product-navigator/csw/record/_search) is key in terms of being able to list the layer in the panel (note: I can get tiles from geoserver, but adding the layer in productDecorations.json file is not enough in the client in order to see it listed in panels)

**Comment by jemacchi** [comment]
@randomorder based on Stefano comments [here](https://cgi-pathfinders.atlassian.net/browse/W9-39?focusedCommentId=14427) I think that in order to be able to see those [2 layers ](https://github.com/geosolutions-it/eumetsat-EOWS/issues/462#issuecomment-764728297) completly integrated in the client, it's required to have those 2 layers included in what Stefano calls  "the product navigator catalogue" (I asked him for details on that and also asked if he can confirm that those 2 layers are available in dev environment)

**Comment by randomorder** [comment]
Please check the feedback from CGI

**Comment by jemacchi** [comment]
> Please check the feedback from CGI

I checked when saw the email and the attached spreadsheet (sent on email) still contains an error (I mentioned that [here](https://github.com/geosolutions-it/eumetsat-EOWS/issues/462#issuecomment-764882857). I fixed names in [the copy of the spreadsheet](https://docs.google.com/spreadsheets/d/1i2gLyWd6SPYSWDj_OWh3mjGhh3Px-md0/edit#gid=420042348) that we have) 
Also it does not contain the definition of layer  mumi:wideareacoverage_rgb_natural_jpeg  (no codes for it, so in productDecorations.json file, not sure what codes to use or not semantic of that layer. Need context)

I can ask for both things to CGI (on email) but not sure if I should proceed or not. @simboss  ?

**Comment by randomorder** [comment]
is this still pending @jemacchi ? did you get the information you need?

**Comment by jemacchi** [comment]
> is this still pending @jemacchi ? did you get the information you need?
@randomorder 
yes, still pending. 
I think that we need to sync with @simboss  first (about the "_jpeg" layer and the names).

**Comment by simboss** [comment]
Close the cache cleaning script then we need to push on this one as well.
So come back to me once we have the other things done.

**Comment by randomorder** [comment]
This in is the hands of CGI /EUM now
