### ISSUE TITLE
Review Download Limits with Daniele

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/eumetsat-EOWS#480]
We want to understand how the download limits are computed and why they are triggering for layer 'copernicus:sentinel3b_olci_l1_rgb_fullres'

![image.png](https://images.zenhubusercontent.com/5cd59eb418690954352b7621/baf4b677-499d-4970-aa4f-cbfeb5dc44d1)

Configuration as follows:
```
# Max #of features
maxFeatures=320000
#8000 px X 8000 px
#rasterSizeLimits=128000000
rasterSizeLimits=2200000000
#8000 px X 8000 px (USELESS RIGHT NOW)
writeLimits=20.000.000.000
# 3.0GB
hardOutputLimit=20.000.000.000
# STORE =0, BEST =8
compressionLevel=8
```

Nearest match is enabled 
![image.png](https://images.zenhubusercontent.com/5cd59eb418690954352b7621/6a0ae11d-2deb-44d6-a019-9d5eeb24de58)

The time I used in my tests is `2021-07-08T23:19:00.000Z`

I've prepared a minimal platform independent binary with EUM's geoserver war, datadir and granules to test this locally. It's available on demo at `/home/dromagnoli/geoserver-2.16.3-bin_eum_limits.7z`

**Comment by randomorder** [comment]
There is a matching JIRA issue [here](https://cgi-bds.atlassian.net/browse/AH-11)

Project code is `C068-EUMETSAT-CGI-2021-Ad_Hoc_WP7`

**Comment by randomorder** [comment]
```
curl 'http://localhost:8080/geoserver/ows' \
  -H 'Content-Type: text/plain' \
  --data-raw $'<?xml version="1.0" encoding="UTF-8"?>\n    <wps:Execute version="1.0.0" service="WPS"\n            xmlns:wps="http://www.opengis.net/wps/1.0.0"\n            xmlns="http://www.opengis.net/wps/1.0.0"\n            xmlns:gml="http://www.opengis.net/gml"\n            xmlns:ogc="http://www.opengis.net/ogc"\n            xmlns:ows="http://www.opengis.net/ows/1.1"\n            xmlns:wcs="http://www.opengis.net/wcs/1.1.1"\n            xmlns:wfs="http://www.opengis.net/wfs"\n            xmlns:xlink="http://www.w3.org/1999/xlink"\n            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"\n            xsi:schemaLocation="http://www.opengis.net/wps/1.0.0 http://schemas.opengis.net/wps/1.0.0/wpsAll.xsd">\n        <ows:Identifier>gs:DownloadEstimator</ows:Identifier>\n        <wps:DataInputs>\n            <wps:Input>\n                <ows:Identifier>layerName</ows:Identifier>\n                <wps:Data>\n                    <wps:LiteralData>copernicus:sentinel3b_olci_l1_rgb_fullres</wps:LiteralData>\n                </wps:Data>\n            </wps:Input>\n            <wps:Input>\n                <ows:Identifier>filter</ows:Identifier>\n                <wps:Data>\n                    <wps:ComplexData mimeType="text/plain; subtype=cql">time = 2021-07-08T23:19:00.000Z</wps:ComplexData>\n                </wps:Data>\n            </wps:Input>\n        </wps:DataInputs>\n        <wps:ResponseForm>\n            <wps:ResponseDocument>\n                <wps:Output>\n                    <ows:Identifier>result</ows:Identifier>\n                </wps:Output>\n            </wps:ResponseDocument>\n        </wps:ResponseForm>\n    </wps:Execute>' \
  --compressed
```

**Comment by dromagnoli** [comment]
Ok. I managed to replicate it locally once having enough granules to cover whole world bbox.
The problem is due to this:

Area to read or target image size exceeds maximum integer value: 2147483647
Download failed

It was already happening on another project when they needed to do huge downloads:

The investigation on that resulted into this:
-----------------------------------------------
The corresponding code is in the file is RasterEstimator.java:

// If the area to read or the target image size are above Integer.MAX_VALUE, false is
// returned, as raster processing operations (e.g. Crop, Scale) may fail if image size exceeds integer
// limits
long targetArea;
Integer[] targetSize = scaling.getTargetSize();
if (targetSize[0] != null && targetSize[1] != null) {
    targetArea = (long) targetSize[0] * targetSize[1];
} else {
    targetArea = areaRead;
}
if (areaRead >= Integer.MAX_VALUE || targetArea >= Integer.MAX_VALUE) {
    if (LOGGER.isLoggable(Level.FINE)) {
        LOGGER.log(
                Level.FINE,
                "Area to read or target image size exceeds maximum integer value: "
                        + Integer.MAX_VALUE);
    }
    return false;
}

It has been introduced 5 years ago as a mitigation of
https://osgeo-org.atlassian.net/browse/GEOS-7230

Basically, the mosaic operation might fail when dealing with the underlying ROIs, especially when invoking a getAsImage on a ROIShape instance. The ROIShape will internally create a ROI Image as big as the referring image, so it might throw an exception when setting up the sampleModel due to width or height too big to be represented as integers.

This jai-ext ticket could help in eliminating that limitation: geosolutions-it/jai-ext#155
since ROIGeometry uses a tiled layout instead, where the sampleModel is actually setup on top of the tileWidth and tileHeight.

-----------------------------


We might add a flag to remove that control and see if the mentioned problem still occurs or not.
Several things have been changed in the last years so there might be the case that ROIShape isn't used anymore.

**Comment by simboss** [comment]
@dromagnoli too many might for this investigation to be closed.

Please, spend more time on this and let's come up with a plan to fix this, whatever it takes (shape fixes included).
Notice that we need to push a fix to the EUM branch which is using GS 2.16.

Let us know how it goes.

**Comment by dromagnoli** [comment]
I think that we need to remove every reference to ROIShape in jai-ext, geotools, geoserver and replace it with ROIGeometry.
At that point no risk of having a single huge image will occur anymore (that was occurring when doing ROIShape.getAsImage()) since ROIGeometry uses tiling.
Therefore, the constraint on numbers being less then Integer.MAX_VALUE will be removed and the Estimator will not complain anymore (provided that the limits configured on download.properties allow for that whole world request).

So steps should be:

1. Update ROIGeometry to support a constructor based on Shape
2. Check for any ROIShape method being used that is actually missing in ROIGeometry
3. Replace any usage of ROIShape with ROIGeometry in jai-ext
4. Replace any usage of ROIShape with ROIGeometry in GeoTools
5. Replace any usage of ROIShape with ROIGeometry in GeoServer (if any)
6. Setup some performances test involving ROIs 
7. Run and compare them when using old code (based on ROIShape) with respect to new code (based on ROIGeometry) to check performances differences (focusing on whether things get slower) 
8. (Optional depending on 7) investigate on performances difference and work on that.
9. Release jai-ext
10. Update GT/GS and the related EOWS-158 branches

**Comment by simboss** [comment]
Thx @dromagnoli can you give a ballpark?

**Comment by simboss** [comment]
@randomorder let's discuss this asap for EUM as well.

**Comment by dromagnoli** [comment]
I can do a quick test (in a couple of hours) to disable that Integer.MAX_VALUE check and see if the download goes well. There might be the case that the huge download isn't involving any ROI intersection check which is the one triggering a ROIShape.getAsImage raising that numeric problem.

**Comment by dromagnoli** [comment]
Test done. 
I did a couple of test requests and it worked without any issue.
I'm attaching here the modified file in case @randomorder want to do some testing with their client on their samples with the modified jar (the one skipping the Integer.MAX_VALUE check) to see if there is any different request that might actually fail.

**Comment by dromagnoli** [comment]
[gs-wps-download-2.16-SNAPSHOT.jar.zip](https://github.com/geosolutions-it/eumetsat-EOWS/files/6861379/gs-wps-download-2.16-SNAPSHOT.jar.zip)

**Comment by simboss** [comment]
let us know how it goes @randomorder

**Comment by randomorder** [comment]
Initial test looks good

After raising the limits I get:

![image](https://user-images.githubusercontent.com/5264230/127686696-568d4f16-0dd3-4df8-89dd-b8f6c757ff43.png)
![image](https://user-images.githubusercontent.com/5264230/127686775-691457b5-04df-4236-878a-6194b71d22d0.png)
![image](https://user-images.githubusercontent.com/5264230/127686845-0b0210ec-f7c4-47a1-a70b-7d6dfd3b28c4.png)

**Comment by simboss** [comment]
great @randomorder. let's test it a little more and let's deliver this to them.
Let them know that we are fixing this for free @randomorder 

@dromagnoli shall we release this fix to the core geoserver and backport to the various brnaches?

**Comment by dromagnoli** [comment]
@simboss 
that update was simply removing the MAX_INT Check but the ROIShape usage is still around so there might be corner cases where it is being used and eventually make the download fail.
I think that we can set a System Property to disable/enable that check while waiting on scheduling some time for the ROIShape replacement with ROIGeometry.
So in case someone get the same issue, he might disable the MAX_INT check and see if things go better. 

Note that, before replacing  ROIShape with ROIGeometry (that would be the real fix), in the worst scenario, an exception can be thrown due to the MAX_INT check or, once removed, on the ROIShape usage hitting a huge image

**Comment by dromagnoli** [comment]
@randomorder done

**Comment by randomorder** [comment]
ty @dromagnoli

**Comment by randomorder** [comment]
deployed
